### ISSUE TITLE
Epitath - renderProps 新用法

### ISSUE THREAD

**Issue by grsabreu** [dt-fe/weekly#106]
**[一種在React中共享功能的新方法：《Epitath》](https://medium.com/astrocoders/epitath-in-memoriam-render-props-and-hocs-9f76dd911f9e)**
本文宣布了一種在React中共享功能的新方法.

**Comment by grsabreu** [comment]
這是我的第一個貢獻, 對不起我的中文不好 😅

**Comment by crimx** [comment]
The idea looks refreshing. One major issue is the implementation of immutable generator, which has to keep cloning and growing the history of values.

> The runtime complexity will be quadratic in the number of `yield` expressions to be evaluated.

Also side-effects control in generator could be an issue especially with all the async calls (I think. Could be addressed by adopting reactive libraries?).

**Comment by grsabreu** [comment]
>The runtime complexity will be quadratic in the number of yield expressions to be evaluated.

yes, I also agree that this is the biggest issue now if people abuse of its usage

>Also side-effects control in generator could be an issue especially with all the async calls (I think. Could be addressed by adopting reactive libraries?).

I don't think the side-effects are an issue if you always scope them in a React stateful component only and handle from the implementation

**Comment by ascoders** [comment]
Sorry for my late comments. `Epitath` is a amazing lib to deal with "render props callback hell" in addition to composing component.

But it seems i can't use it locally. I should first use `epitath` to generate a composed component, so it can't be inserted directly into JSX like `render props`.

**Comment by ascoders** [comment]
@grsabreu React Hooks is almost looks like Epitath write in sync code!

**Comment by ascoders** [comment]
我认为 Epitath 就是 React Hooks 的原型。

**Comment by xialvjun** [comment]
```jsx
function epitath(gen_fn) {
  return (...args) => {
    const gen = gen_fn(...args);
    function render(children_args) {
      let { value, done } = gen.next(children_args);
      if (done) {
        return value;
      }
      return React.cloneElement(value, null, render);
    }
    return render();
  }
}
```

这种实现能够避免每次都创建新的 `Component`，而且更简单。 @ascoders
