### ISSUE TITLE
精读《用 Reduce 实现 Promise 串行执行》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#109]
本周精读的文章是：[why-using-reduce-to-sequentially-resolve-promises-works](https://css-tricks.com/why-using-reduce-to-sequentially-resolve-promises-works/)

Promise.all 可以并行解决处理所有异步 Promise，但 Promise 串行执行却没有现成的 API，本文推荐了 `reduce` 方式解决 Promise 串行执行的思路值得学习。

**Comment by atian25** [comment]
https://github.com/sindresorhus/promise-fun

**Comment by kangenpingmai** [comment]
如果任务队列中的函数都依赖上一个返回值的函数改怎么写呢

**Comment by lesonky** [comment]
> 如果任务队列中的函数都依赖上一个返回值的函数改怎么写呢

```
let userIDs = [1,2,3];

userIDs.reduce( async (previousPromise, nextID) => {
  // 这里可以获取前一个 promise 的返回值
  const previousResolve = await previousPromise;
  // 拿到返回值后可以到下面去用 
  // 第一个返回值是一个空的,因为reduce 的起始值是 Promise.resolve(),
  // 如果要给第一个函数也加一个参数,可以用 Promise.resolve('XXX'),
  // 这样第一个函数调用的时候也会有一个参数 XXX
  return methodThatReturnsAPromise(nextID,previousResolve);
}, Promise.resolve());
```

**Comment by c690554125** [comment]
复杂一点如，多个任务，得按照顺序来交互，每个任务又是异步，这个场景也能用到串行Promise
