### ISSUE TITLE
精读《Typescript 3.2 新特性》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#117]
Ts 发布 3.2 了，评论评论新特性吧，官方文档地址：https://blogs.msdn.microsoft.com/typescript/2018/11/29/announcing-typescript-3-2/

**Comment by eos3tion** [comment]
* [`strictBindCallApply`](https://blogs.msdn.microsoft.com/typescript/2018/11/29/announcing-typescript-3-2/#strictbindcallapply) 
这个挺有用，一开了以后，马上发现一些接口调整后，遗漏的代码改动，不过目前不支持直接把 arguments 作为参数赋值，会提示无法将 Argument of type 'IArguments' is not assignable to parameter of type XXX

* [`Improved narrowing for tagged unions`](https://blogs.msdn.microsoft.com/typescript/2018/11/29/announcing-typescript-3-2/#improved-narrowing-for-tagged-unions) 
这个能有更多新玩法了，以前一些不好做类型约束的，现在做起来更方便，也更容易重构代码

**Comment by ascoders** [comment]
[精读《Typescript 3.2 新特性》](https://github.com/dt-fe/weekly/blob/master/84.%E7%B2%BE%E8%AF%BB%E3%80%8ATypescript%203.2%20%E6%96%B0%E7%89%B9%E6%80%A7%E3%80%8B.md)
