### ISSUE TITLE
精读《手写 SQL 编译器 - 智能提示》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#118]
总结了以前 SQL 编译器文章，详细介绍如何做智能提示。

**Comment by atian25** [comment]
issue 里面建议加下 URL 指向文章

**Comment by ascoders** [comment]
[精读《手写 SQL 编译器 - 智能提示》](https://github.com/dt-fe/weekly/blob/master/85.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%89%8B%E5%86%99%20SQL%20%E7%BC%96%E8%AF%91%E5%99%A8%20-%20%E6%99%BA%E8%83%BD%E6%8F%90%E7%A4%BA%E3%80%8B.md)

**Comment by wendzhue** [comment]
读完了这个系列的文章，学到很多～

**Comment by navisoftware** [comment]
请问 @alife/monaco-sql-plugin 这个插件在哪里可以下载？

**Comment by ascoders** [comment]
@navisoftware 那个是内部的，开源的是 https://github.com/ascoders/syntax-parser

**Comment by navisoftware** [comment]
我使用 https://github.com/ascoders/syntax-parser/blob/master/src/demo/sql-parser/mysql/parser.ts 来编写自己的mysql代码提示。
我发现 insertStatement 不提示表源和字段源。
  return chain('insert', optional('ignore'), 'into', tableName, optional(selectFieldsInfo), [selectStatement]);

我发现这个tableName并未去调用 onSuggestTableNames
const tableName = () => {
  return chain([
    chain(stringOrWord)(),
    chain(stringOrWord, '.', stringOrWord)(ast => {
      return [ast[0], ast[2]];
    }),
  ])(ast => {
    if (ast[0].length === 1) {
      return createTableName({
        namespace: null,
        tableName: ast[0][0],
      });
    }
    if (ast[0].length === 2) {
      return createTableName({
        namespace: ast[0][0],
        tableName: ast[0][1],
      });
    }
  });
};

我换成 tableSourceItem 或者 tableSource 或 tableSources 都不行。我想问一下作者，如果我要在非select * from 这种结构中提示我在前端构建的 onSuggestTableNames或 onSuggestTableFields 方法呢？望告知，感谢！

**Comment by DuShuYuan** [comment]
[syntax-parser](https://github.com/ascoders/syntax-parser)  demo里只有select能提示表名字段名，其他语句都提示不了啊
