### ISSUE TITLE
cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by frankshin** [dt-fe/weekly#120]
为什么我按照文中的语法测试，会报错：cannot read property 'state' of undefined。貌似state不加入到参数中，不会绑定到reducer？
reducers: {
  increment: payload => this.state + payload,
  decrement: payload => this.state - payload
}

**Comment by ascoders** [comment]
weekly 只做前沿话题讨论，具体框架问题可以去对应项目提交 ISSUE。

如果是精读文章提到的相关代码，请指明对应哪篇精读，以及详细环境，使用了什么框架，这样两个回合就能说清楚，否则一问一答效率比较低。
