### ISSUE TITLE
精读《Caches API》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#124]
本周精读的文章是：[cache-api](https://bitsofco.de/cache-api-101/)

**Comment by giscafer** [comment]
一直关注着，为了方便，近期开发了个小程序，并把《前端精读周刊》订阅加入了小程序周刊列表。感谢@ascoders 大佬一直坚持分享
![qr252](https://user-images.githubusercontent.com/8676711/51069422-cee4f780-1669-11e9-937c-33055af05eef.jpg)

<img src="https://user-images.githubusercontent.com/8676711/51069444-41ee6e00-166a-11e9-84a2-af2dec5dc1f7.jpg" width="350px"/>

**Comment by AngusFu** [comment]
仿佛看了奇舞周刊 😄 周刊君这厢有礼了
