### ISSUE TITLE
精读《极客公园 2019》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#126]
本周前端圈子推荐的文章质量都一般，正好年前参加了极客公园 IF 2019 大会，利用精读机会谈谈感想。

这是极客公园 2019 的内容介绍：[WHY NOT](http://if.geekpark.net/)。

最近正在读萨提亚的 《刷新》 这本书，和极客公园所介绍的前沿 VR AR CR MR XR 都是新的前端交互形式，前端领域正越来越广。终端、服务、AI 这三者将成为未来十年的主旋律，这些最前沿的技术发展都与前端息息相关。

欢迎交流。

**Comment by baxtergu** [comment]
全篇认真读完，感谢笔者的无私分享和总结。

Typo:
在 “一个 30 多年始终保持创造力的组织，经历了什么？” 章节中的第一段话：
迪士尼动画的创意给我们的印象深刻，这次迪士尼的总裁 Ed Catmull 带给我们最有启发的一点，就是迪士尼的创新来自于快速 失措（->试错）。
