### ISSUE TITLE
精读《正则 ES2018》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#127]
ES2018 推出了正则表达式的第九版规范，让 JS 正则功能更强大，也更易读了！

原文：[New JavaScript Features That Will Change How You Write Regex](https://www.smashingmagazine.com/2019/02/regexp-features-regular-expressions/)

一起了解让人激动的新特性吧！

```tsx
const re = /(?<year>\d{4})-(?<month>\d{2})-(?<day>\d{2})/;
const [match, year, month, day] = re.exec('2020-03-04');

console.log(match);    // → 2020-03-04
console.log(year);     // → 2020
console.log(month);    // → 03
console.log(day);      // → 04
```

---

[精读《正则 ES2018》](https://github.com/dt-fe/weekly/blob/master/91.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%AD%A3%E5%88%99%20ES2018%E3%80%8B.md)

**Comment by muzea** [comment]
断言支持逆向环视让人印象深刻，edge上面整个app直接崩溃了。。。

**Comment by ascoders** [comment]
毕竟 Edge 还不支持，不过 app 崩掉有点厉害了，说明正则执行的风险比较高。
