### ISSUE TITLE
精读《Serverless 给前端带来了什么》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#135]
正好公司内部在推 Serverless，我也读了一些相关的书和文章，希望在前端圈推广一下 Serverless 理念。

---

[精读《Serverless 给前端带来了什么》](https://github.com/dt-fe/weekly/blob/master/94.%E7%B2%BE%E8%AF%BB%E3%80%8AServerless%20%E5%B8%A6%E6%9D%A5%E4%BA%86%E4%BB%80%E4%B9%88%E3%80%8B.md)

**Comment by atian25** [comment]
链接呢~

**Comment by ascoders** [comment]
![image](https://user-images.githubusercontent.com/7970947/53942484-dc60b000-40f5-11e9-904f-da9d6f6c3ce1.png)

文章链接在这，用微信读书扫一扫。

**Comment by atian25** [comment]
不，我指精读感言呢？只看到 93，没看到 94

**Comment by ascoders** [comment]
这是 94 期，下周一发布，这周一发布的是第 93 期～

**Comment by zeromake** [comment]
@ascoders 链接错了是 https://github.com/dt-fe/weekly/blob/master/94.%E7%B2%BE%E8%AF%BB%E3%80%8AServerless%20%E7%BB%99%E5%89%8D%E7%AB%AF%E5%B8%A6%E6%9D%A5%E4%BA%86%E4%BB%80%E4%B9%88%E3%80%8B.md

**Comment by ascoders** [comment]
@zeromake 已修正，谢谢！

**Comment by giscafer** [comment]
后端有 Microservice、Serverless，前端也有人在研究实践微前端（Micro-Frontend），阿里内部那么多项目/系统，各种技术可能都有，有没有比较大异构系统整合情况，可以来一次解决经验、方案分享。个人之前学习了解过一些。
[微前端 Micro-Frontend](https://github.com/giscafer/front-end-manual/issues/20)

**Comment by ascoders** [comment]
@giscafer 内部的话从开发框架、工程平台到搭建平台、数据平台都有。

搭建平台和数据平台都是可视化搭建类场景，解决不同业务问题，基本上可以分为三类吧：类似问卷的简单表单场景搭建工具、报表搭建工具、复杂后台系统搭建工具。输出方式有应用、代码、iframe 等。

工程平台也可以拆解为前端中间件+开发框架，前端中间件就比如云构建系统、review 系统，开发框架逐渐沉淀为一些一体化框架，比如 [pri](https://github.com/prijs/pri) [umi](https://github.com/umijs/umi) 就是一些例子，当然内部会套一层业务环境，这个无可替代。

工程体系现在往云+端发力，也就是云到端（WebUI 或工程管理工具）、或者端到云（IDE 插件）。更多可以参考 Coding 和腾讯合作的 Cloud Studio 吧，解决工程体系最后一公里问题。

**Comment by unclexiao** [comment]
请问一下，微信小程序的[云开发/云函数](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/basis/getting-started.html)是否算的上Serverless的简单实现，在此之前，前端开发从来没有离数据库这么近。

如果不算，那它还欠缺什么，触发器/事务/并发处理这些么？

**Comment by unclexiao** [comment]
请问一下，微信小程序的[云开发/云函数](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/basis/getting-started.html)是否算的上Serverless的简单实现，在此之前，前端开发从来没有离数据库这么近。

如果不算，那它还欠缺什么，触发器/事务/并发处理这些么？

**Comment by ascoders** [comment]
@unclexiao 微信小程序的云函数算 FAAS。

**Comment by giscafer** [comment]
最近比较火的 [code-server](https://github.com/codercom/code-server) 应该也用了Serverless

**Comment by liuxsen** [comment]
这太牛逼了

发自我的 iPhone

**Comment by ascoders** [comment]
@giscafer 和 [code-server](https://github.com/codercom/code-server) 类似做的比较好的也有 Coding 的云 IDE，2019 极客大会上有介绍过：[云开发流程](https://e.coding.net/?utm_source=weekly)

**Comment by giscafer** [comment]
@ascoders 嗯，这个有了解过

**Comment by xmsz** [comment]
内容非常好 现在遇到Serverless很大问题
目前场景来说
- 云函数处理
- SSR

而其他场景真的有点不科学的样子

如果拿来BFF，那真的是浪费资源

如果拿来当全栈，明明2个人效率更高，为什么要1个人开发


除非你是真的只有1个人的情况...
