### ISSUE TITLE
精读《useEffect 完全指南》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#138]
本周精读的文章是：[a-complete-guide-to-useeffect](https://overreacted.io/a-complete-guide-to-useeffect/) - `useEffect` 全面解析。

---

[精读《useEffect 完全指南》](https://github.com/dt-fe/weekly/blob/master/96.%E7%B2%BE%E8%AF%BB%E3%80%8AuseEffect%20%E5%AE%8C%E5%85%A8%E6%8C%87%E5%8D%97%E3%80%8B.md)

**Comment by jiajiafish** [comment]
看了这篇文章针对您的react技术跪了，太牛逼了，请受我一拜。

**Comment by konglx90** [comment]
> 看了这篇文章针对您的react技术跪了，太牛逼了，请受我一拜。

这是翻译的，原文是react hooks的开发者写的

**Comment by ascoders** [comment]
是的，原文在 Issue 和文章里都给出了。希望大家能把别人的知识吸收，成为自己的知识。
