### ISSUE TITLE
精读《react-easy-state 源码》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#144]
[react-easy-state](https://github.com/solkimicreb/react-easy-state) 和 [dob](https://github.com/dobjs/dob) 一样，都是 [mobx](https://github.com/mobxjs/mobx) 的挑战者。

react-easy-state 重点在其简洁的语法，迷人的双向绑定，深度与 Function Component 的结合。虽然笔者建议大家使用 Immutable 的思维使用 React，但这个库的代码还是值得读一读的。

**Comment by zWingz** [comment]
看了一下, 这个库对于`local state`的用法, 除了修改方式不一样, 我想不到跟`setState`和`useState`还有什么不同

**Comment by ascoders** [comment]
很大不同：

1. 是全局数据流。
2. 双向绑定。
3. 同时支持 Class Component 和 Function Component。

**Comment by dyyz1993** [comment]
黄，你这个库有问题，引入了但没用使用。会导致input输入不了中文，react-easy-state，这个是垃圾库。https://github.com/RisingStack/react-easy-state这个才是正牌的。

**Comment by ascoders** [comment]
原文地址的 github 仓库已经自动跳转到你发的地址啦。
