### ISSUE TITLE
精读 持续集成 vs  持续部署 vs 持续交付  

### ISSUE THREAD

**Issue by huxiaoyun** [dt-fe/weekly#147]
软件开发中 CI/CD 一直是保障项目质量和上线时间点的核武器，如何使用呢？

在日常项目运行过程中有什么心得呢？

常规的敏捷迭代开发如何接入 CI/CD 呢？

让我们一起走进 CI/CD  本周精读的文章是 https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment

**Comment by ascoders** [comment]
标题太长了 @huxiaoyun 精简一下

**Comment by ConardLi** [comment]
您好，可以转载到公众号【code秘密花园】吗，会注明转载来源和作者

**Comment by ascoders** [comment]
@ConardLi 可以。

**Comment by LiYanLance** [comment]
持续部署应该是 Continuous deployment 吧，[图里](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/101.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%8C%81%E7%BB%AD%E9%9B%86%E6%88%90%20vs%20%E6%8C%81%E7%BB%AD%E4%BA%A4%E4%BB%98%20vs%20%E6%8C%81%E7%BB%AD%E9%83%A8%E7%BD%B2%E3%80%8B.md#%E4%B8%89%E5%8D%8F%E4%BD%9C)是不是写错了？

**Comment by ascoders** [comment]
> 持续部署应该是 Continuous deployment 吧，[图里](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/101.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%8C%81%E7%BB%AD%E9%9B%86%E6%88%90%20vs%20%E6%8C%81%E7%BB%AD%E4%BA%A4%E4%BB%98%20vs%20%E6%8C%81%E7%BB%AD%E9%83%A8%E7%BD%B2%E3%80%8B.md#%E4%B8%89%E5%8D%8F%E4%BD%9C)是不是写错了？

对确实写错了。。
