### ISSUE TITLE
精读《V8 引擎 Lazy Parsing》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#148]
本周精读的文章是：[Blazingly fast parsing, part 2: lazy parsing](https://v8.dev/blog/preparser)，这是 V8 急速引擎的第二篇文章，介绍了 V8 如何通过 Lazy Parsing 实现快速解析 JS 代码。

**Comment by huxiaoyun** [comment]
最近node 作者新开了个坑 deno 。要不瞅瞅。
