### ISSUE TITLE
修改标题以支持字母序

### ISSUE THREAD

**Issue by dancerphil** [dt-fe/weekly#152]
现在的顺序：

```
10.精读...
100.精读...
101.精读...
...
11.精读...
12.精读...
```

期望的顺序：

```
010.精读...
011.精读...
012.精读...
...
100.精读...
101.精读...
```

see also: https://github.com/dt-fe/weekly/commit/901e353b22b6c130ed83ccc365933741746ec83e

**Comment by dancerphil** [comment]
如果忙的话我可以提 PR

**Comment by ascoders** [comment]
这样改会影响到所有原文链接地址，有没有更好的方式？

**Comment by Lionad-Morotar** [comment]
mark

**Comment by dancerphil** [comment]
没什么好办法

~~修改文件名后，保留旧文件名做跳转~~，不行的原因在于旧的文件依旧可能会影响排序

只能想到一种，即用 `ghpages / 新分支`，新的链接连到 `ghpages / 新分支`，旧的链接不管，这样可以在保持原有的文件名的基础上排序

**Comment by ascoders** [comment]
@dancerphil 谢谢，不错的办法，我新建了 v2 分支，本周如果没有 PR 我就在周末做一下迁移。

**Comment by ascoders** [comment]
非常感谢 @dancerphil 的贡献！
