### ISSUE TITLE
精读《为什么专家不再关心技术细节》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#153]
其实并没有 《为什么专家不再关心技术细节》 这篇文章，只是笔者自身对做业务线技术开发的思考。

通过观察可以发现，前端技术大佬早期都有很多杀手级技术项目，但渐渐的文章都会转变到偏务虚的方法论，或者比较哲学性的思考。

技术专家一定要持反复轮子或持续发表框架解读的文章吗？不再关注技术细节的他还是你心目中的大佬吗？分享一下你我的思考。

**Comment by zhoukekestar** [comment]
刚好前几天，老板跟我们讲过类似的话题，分享一下。
为什么不再需要？专家之所以为专家，是要站在比工程师更高的角度看待问题，并能在一些**岔路口做一些方向性判断**，这个判断的影响面，少则 1 ~ 2 年，多则 3 ~ 5 年甚至更长，这就需要专家型人才能从架构、模式甚至哲学意味偏虚的内容在里面。而至于细节，是工程师实施过程中的落地的一些问题，这也是专家差异化存在的意义。
当然，也需要辩证看待，过虚而**忽略细节**的话，在方向判断上也会有更大概率的误判。物极必反，这必然是一个平衡的过程。

**Comment by Lionad-Morotar** [comment]
按照知乎的规矩, 先问是不是/ 啊 不好意思 我走错片场了

**Comment by hefei00** [comment]
可以务虚，但是我觉得最好能对业界技术发展有了解，能从更高一级的视野看待技术的发展。太虚了的话，就喝普通的鸡汤没区别了

**Comment by nanfs** [comment]
这个问题  专家不再关心技术细节? 其实是技术细节关系有必要吗? 必须吗? 我觉得不是必须,但可以必要. 专家如果是架构方面,需要了解技术原理,差别和取舍. 具体主要实现主要的可以深入(如果你想的话) 主要还是要再宏观架构上面. 保证方向和结构. 当然如果是技术专家,对每个技术都刨根问底,对技术触类旁通.不去关心细节很难做到到.

**Comment by jorexQ** [comment]
国外很多大佬，到后期或者老年了，一样对细节很认真。
只是这个认真不是对工程实现上的，更多是对标准和协议方向的。
你看国外很多标准和协议都是有自己的基金或协会的，这些基金会和协会的委员，都是各个行业和方向的专家和大佬，他们在一起推动某些标准和协议前进。
你看看那些标准和协议，都是几百上千页的文档和说明，这些都不是一般架构师和大佬能完成的。
现在中国缺的就是标准和协议。

**Comment by ascoders** [comment]
@jorexQ 标准协议不属于技术细节了，属于宏观设计，而且能影响到很多人。不过大佬在制定标准时都是能伸能缩，既能宏观制定标准，又能深入到代码层面快速讨论 Demo。

**Comment by superbiger** [comment]
个人认为应该思考下解释性与方向性之间区别和联系。例如:从头造轮子是对于一个已有事物的解释，普通工程师很容易错误理解这种可解释性的东西是前进方向，从而纠缠于技术细节当中去。即使是产品或是管理岗位也有将解释性误当做方向。
方向是建立一个优化问题，本身问题不是一个优化问题就不可能有解。细节的思考能够逐步修正要定义的优化问题本身。不论是技术还是业务或是其他。

**Comment by AndroidInternal** [comment]
所以这里的技术细节需要做一个定义。如果单纯的只有务虚、哲学思考，我认为talk is cheap.

**Comment by eyea** [comment]
人要学会在合适的位置做合适的事情，专家如此，我们亦然。

**Comment by tomzhang** [comment]
我个人认为专家是站在整个产品形态的角度处理问题和看待问题。不注重细节是比如细化到接口具体实现部分。但是整个接口定义和标准化还是需要掌控和把握的。很多专家也同时兼任技术负责人监管资源协调和跨部门协作。很难再在细节化的某些实现上进行代码层面的把控了。

**Comment by ascoders** [comment]
@tomzhang 定期做代码 review～

**Comment by random-yang** [comment]
细节不是也分很多种吗？关键细节，还是非关键细节，不能一概而论吧。

**Comment by ascoders** [comment]
@random-yang 对的，其实之前说的不是很严谨，技术细节代表的含义可以很多，框架实现原理算技术细节，if else 怎么写算技术细节，多一个空行少一个分号算技术细节，甚至用什么框架都算技术细节。当产品与技术争执的时候，“我不关心技术细节” 是产品很容易说出的话，但换成技术同学说出这句话，就觉得不妥当了。

但一个产品是由产品、运营、前端后端、算法、测试、视觉、交互、管理人员等一系列不同职能分工人员实现的，技术细节重不重要，要看你当时说话的语境。如果你在做产品决策，由于不能因为技术实现影响产品规划，技术细节就是不重要，但如果你在做技术决策或者技术实现，技术细节就很重要。

这个 issue 要讨论的是，不同场景关注点是不同的，你在不同阶段要关注的细节也不一样。如果你成为了技术专家或者架构师，还总把时间花在具体某个 API 如何命名，纠结一个逻辑分一个文件还是两个文件，你可能在把时间花在低人效的事情上了，长期下去，你的产出就会很低。

那专家是不是一定不要关注细节呢？那也未必，其实要看如何关注。如果某个 API 的命名会大大影响调用者的使用效率，如果一个逻辑分成一个文件还是两个文件关系到了设计模式，影响到整个产品的架构设计，那你去关心这些细节就是应该的。

我们要逐渐摒弃的是关注那些不值得投入精力的细节，像 @jorexQ 所说的协议细节就是值得花时间投入的，具有重大投入产出比的细节，在这个细节上花再多精力都不过分。性价比低的细节要用培训、机制、流程来解决，这也是团队建设者或者技术专家要做的事情，之后，你就可以把时间花在重要的细节上了。

最后，不要纠结哪些属于细节，哪些不属于细节，俗话说细节决定成败，不关注细节肯定是不对的，重要的是你要能识别出当下哪些细节是你要关心的，随着你的成长，你要关注的细节应该不断变化。

**Comment by random-yang** [comment]
> 那专家是不是一定不要关注细节呢？那也未必，其实要看如何关注。如果某个 API 的命名会大大影响调用者的使用效率，如果一个逻辑分成一个文件还是两个文件关系到了设计模式，影响到整个产品的架构设计，那你去关心这些细节就是应该的。

赞同～
