### ISSUE TITLE
精读《Optional chaining》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#165]
8天前，[optional-chaining](https://github.com/tc39/proposal-optional-chaining) 进入了 stage2，TS 也有 [进一步动作了](https://github.com/microsoft/TypeScript/issues/16)，本周深入阅读一下官方文档。

---

[精读《Optional chaining](https://github.com/dt-fe/weekly/blob/v2/107.%E7%B2%BE%E8%AF%BB%E3%80%8AOptional%20chaining%E3%80%8B.md)

**Comment by eos3tion** [comment]
TS团队说了，要到stage3才去实现，近期难有动作的。  
期待TS实现这个功能已经期待了几年了。

**Comment by ascoders** [comment]
从 Issue 里好像没有明确表态 stage3 才会引入，只是说了 async/await 是在 stage3 才引进的，看来大家都很期待这个特性。

不过对于语言解析系统来说，实现确实挺有难度，比如草案中提到的这种情况：

`foo?.3:0` 需要正确解析为 `foo ? .3 : 0`，需要升级解析器 `lookahead` 功能，也许指的是 [LALR parser](https://en.wikipedia.org/wiki/LALR_parser)

函数用起来有点别扭 `c?.(x)` 以及一些不支持的用法 `a?.b = c` 都需要详细讨论并理解后才保证正常使用。

感觉本质上是 `?.` 这个看似简洁的语法带来的歧义比较大，而且不能想当然的用在所有场景中。

**Comment by ystarlongzi** [comment]
`?.` 这个运算符是不是还叫做 [`Safe navigation operator`](https://en.wikipedia.org/wiki/Safe_navigation_operator)

**Comment by giscafer** [comment]
`?.` 的动作angular2+ 就一直支持，用着很爽。

**Comment by eos3tion** [comment]
@ascoders  今天到 `stage 3`了，被纳入`typescript`有希望了。

**Comment by iFwu** [comment]
> @ascoders 今天https://github.com/tc39/proposal-nullish-coalescing 到 `stage 3`了，optional chain估计也快了，被纳入`typescript`有希望了。

我记得TypeScript官方从来没说过进入到某Stage就要merge这个功能，他们还是会按照自己的节奏。。包括那个private class member，讨论了好久还是目前没看到有进

**Comment by eos3tion** [comment]
@iFwu 官方之前有个issue里面提到过，至少要到 `stage 3`，如果我没记错，好像是`Numberic_splite`特性的帖子里面，之前本来在 `stage 3`，ts团队就放出来了，结果发现了个问题会和css冲突，恢复到了`stage 2`，ts又把功能给屏蔽了，直到后面重新进入`stage 3`，才恢复功能。

**Comment by iFwu** [comment]
> @iFwu 官方之前有个issue里面提到过，至少要到 `stage 3`，如果我没记错，好像是`Numberic_splite`特性的帖子里面，之前本来在 `stage 3`，ts团队就放出来了，结果发现了个问题会和css冲突，恢复到了`stage 2`，ts又把功能给屏蔽了，直到后面重新进入`stage 3`，才恢复功能。

嗯😂，他们还说不应该先放出decorators和class member呢，然而大家都用的很香，甚至作为很大的卖点了。
stage 3是必要非充分条件，应该是只有到了才有资格进。

我感觉TS在这点上还是有点不灵活，不方便对语法进行扩展，这对以后的ECMAScript发展可能会有所损害——不能像Babel那样只要有能实现的提案，就可以写一个transform插件去使用它。

**Comment by ascoders** [comment]
TS 是不灵活，但也不是坏事，Babel 可以自己造个插件支持不存在的语法，反而会造成技术孤岛。
