### ISSUE TITLE
精读《Vue3.0 Function API》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#173]
Vue3.0 的发布造成了不小的震动，为什么 React Hooks 的发布没有造成这种轩然大波？

本周先来详细了解 Vue3.0 的改变 [Vue Function API 汇总](https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md)

---

[精读《Vue3.0 Function API》](https://github.com/dt-fe/weekly/blob/v2/109.%E7%B2%BE%E8%AF%BB%E3%80%8AVue3.0%20Function%20API%E3%80%8B.md)

**Comment by masx200** [comment]
什么时候可以下载到vue3.0的测试版呢?

**Comment by ascoders** [comment]
下半年等消息吧，据说 2019 年会发布
