### ISSUE TITLE
精读《Inject Instance 源码》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#176]
[injrect-instance](https://github.com/ascoders/inject-instance) 是笔者写的一个依赖注入库，利用装饰器实现依赖注入。

并没有依赖什么 JS 特性，仅仅介绍一种依赖注入实现的思路，希望对大家的框架实现有帮助。

---

[精读《Inject Instance 源码》](https://github.com/dt-fe/weekly/blob/v2/110.%E7%B2%BE%E8%AF%BB%E3%80%8AInject%20Instance%20%E6%BA%90%E7%A0%81%E3%80%8B.md)

**Comment by chenqiongqiong** [comment]
这就是AOP吗
