### ISSUE TITLE
精读《深入理解 React 高阶组件》

### ISSUE THREAD

**Issue by BlackGanglion** [dt-fe/weekly#18]
在 React 中，高阶组件（higher-order component，HOC）是一种复用组件逻辑的进阶技巧，在 React 众多类库中也有广泛的使用，本周精读让我们一起来聊聊 React 高阶组件。

文章地址：[https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e](https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e)

**Comment by alcat2008** [comment]
提到 HOC，首先想到的就是这篇文章 [基于Decorator的组件扩展实践](https://zhuanlan.zhihu.com/p/22054582?refer=purerender)，就是 @BlackGanglion 的大作。

Compose + Decorator 的方式确实相当优雅，应用场景包括并不限于组件、函数。

这种模式下，每个 C 都是薄薄的一层，单一职责，维护起来极其方便。

目前我们团队就采用这种模式，省时省力省心。

**Comment by MrPluto** [comment]
弱弱的放一篇 翻译。。 [HOC](https://mrpluto.js.org/2017/03/10/React%E9%AB%98%E9%98%B6%E7%BB%84%E4%BB%B6%E6%8E%A2%E7%A9%B6%EF%BC%88%E8%AF%91%E6%96%87%EF%BC%89/)

然后 [应用](http://rea.tech/reactjs-real-world-examples-of-higher-order-components/)

**Comment by jasonslyvia** [comment]
希望大家能在这里分享观点，而不是简单的分享资料。

**Comment by monkingxue** [comment]
## 从 type system 的角度来看看 HOC

我想换个角度来谈谈我对 HOC 的浅见。

在我看来，React 中产生 HOC 简直是天经地义的事情，原因其实很简单，在 React 中组件是 first class 的，这样我们就可以利用 **type system** 的眼光来看待 component。

根据业务来划分，我们一种组件就是一种 type，借用 haskell 中的一个概念，这个组件的 kind 是 `*`，那么很明显，HOC 的 kind 就是 `*->*`。众所周知，kind 是对于 type 的抽象，React 中之所以出现这种抽象，很明显是业务的需要，换句话来说，我们的业务是基于 type system 构建的，我觉得这对于前端是一个巨大的进步。为什么呢？因为借助 type system，我们可以在编译期就静态避免很多 bug。原来的 JS，是 **compile OK，but doesn't work**，其中一个原因是因为 JS 的弱类型，这很好解决，用 TS 能大大缓解这个问题。而另外一个的原因就是业务的无类型。

为什么说业务无类型呢？回想开发 cocos、.NET这些东西的日子，由于语言的 OO 特性，我不得不把业务操作封装在一个个 class 中。过度封装当然不好，但是由于 class 即 type 的特性，我甚至在 extend 一个 class 的时候，就自动完成了 inherient 和 subtype 。当我需要修改某一个业务的 class 的时候，我就不得不去考虑 type 的关系，否则 IDE 直接静态给我一个 error。反观 JS，无论我对一个业务的封装做怎样的修改，IDE 都没什么反应，然后我就只能对着没有反应的页面发呆，再默默地打开 dev tool 一步步断点。而引入 HOC，其实就是加强了业务上的类型关联度，而这种关联度，就是静态检测的保证。

当然，前端的多副作用让**严格**的 type system 基本没有什么用武之地，想想也是，如何在数学中定义一系列副作用的推导关系呢？但是这并不是说 HOC 没什么用处，别忘了那个著名的公式 `view = render(state)`，在一个可以自洽的组件系统中，HOC 是一种很棒的抽象，比如 @BlackGanglion 聚聚文章中所举的 select 和 search 的例子。

唔，脑洞可以大一点，比如我们完全可以利用 HOC 来实现 React 的 **implement** 啊，把操作和 view 分离，让一种业务类型（比如 input）的 dumb component 都 extends input action 的 HOC，既是漂亮的抽象，也有静态类型检查的优点。

当然，最后的最后，**不可过度抽象** 仍是最重要的一点，就我的实践而言，HOC 的抽象成本还是有点高的，在大型项目中，合理使用 HOC 十分有必要，而小型项目嘛，老夫（大雾）写代码就一梭子~

**Comment by camsong** [comment]
原文中也提到了 HOC 和 Parent Component 的区别。对比来看：

React 的范式是：
```
view = render(state)
```

HOC 的范式是：
```
compose(render)(state)
```

parent component 的范式是：
```
render(render(state))
```

因此 @monkingxue 说完全可以利用 HOC 来实现 React 的 implement 啊，把操作和 view 分离，但这样做虽然功能上没问题，但一点也不优雅！谨防过度设计。

View 中逻辑从 DOM 相关性上划分为三种：
1. DOM 相关。建议使用 parent component
2. DOM 不相关，如校验、权限、请求发送、数据转换这类，通过数据变化间接控制 DOM。可以使用 HOC
3. 交叉的部分，DOM 相关，但可以做到完全内聚，即这些 DOM 不会和外部有关联。均可

DOM 的渲染适合使用 parent component，这是 React JSX 原生支持的方式，清晰易懂。最好是能封装成 dumb component 中。
HOC 适合做 DOM 不相关又是多个组件共性的操作。如 Form 中，validator 校验操作就是纯数据操作的，放到了 HOC 中。但展示 Error 信息没有放到 HOC 中。但如果能把 Error 信息展示这些逻辑能够完全隔离，也可以放到 HOC 中。

“请求发送”是另一类 DOM 不相关的场景，react-refetch 的实现就是使用了 HOC，做到了高效和优雅：
```js
connect(props => ({
  usersFetch: `/users?status=${props.status}&page=${props.page}`,
  userStatsFetch: { url: `/users/stats`, force: true }
}))(UsersList)
```
