### ISSUE TITLE
精读《Nodejs V12》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#184]
一起看看 Node12 带来了什么新特性：[Node.js 12: The future of server-side JavaScript](https://blog.logrocket.com/node-js-12/)

---

[精读《Nodejs V12》](https://github.com/dt-fe/weekly/blob/v2/113.%E7%B2%BE%E8%AF%BB%E3%80%8ANodejs%20V12%E3%80%8B.md)

**Comment by atzcl** [comment]
错误语句：
> ... 也给会一定程度上提升网页的运行效率。

修正：
> ... 也会一定程度上提升网页的运行效率。

**Comment by ascoders** [comment]
已合 pr
