### ISSUE TITLE
精读《前端与 BI》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#208]
笔者分享自己在阿里数据中台做 BI 的体验，介绍前端在 BI 领域如何发展。

---

[精读《前端与 BI》](https://github.com/dt-fe/weekly/blob/v2/121.%E7%B2%BE%E8%AF%BB%E3%80%8A%E5%89%8D%E7%AB%AF%E4%B8%8E%20BI%E3%80%8B.md)

**Comment by yanlongliu** [comment]
支持

**Comment by zjcnzxsjy** [comment]
是阿里的quick-bi产品吗

**Comment by martinwithyou** [comment]
说得好

**Comment by NARUTOne** [comment]
BI开发中 🚀

**Comment by Evoque** [comment]
BI分享相关的后续呢

**Comment by ascoders** [comment]
因为 BI 是有一定技术壁垒的商业项目，感觉不太适合拿来做开源分享，如果有对 BI 开发感兴趣可以发简历到 ziyi.hzy@alibaba-inc.com 邮箱！
