### ISSUE TITLE
精读《robot 源码 - 有限状态机》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#209]
[robot](https://github.com/matthewp/robot) 是一个实现有限状态机的库，本期精读会分析其源码以及在业务中的使用场景。

---

[精读《robot 源码 - 有限状态机》](https://github.com/dt-fe/weekly/blob/v2/122.%E7%B2%BE%E8%AF%BB%E3%80%8Arobot%20%E6%BA%90%E7%A0%81%20-%20%E6%9C%89%E9%99%90%E7%8A%B6%E6%80%81%E6%9C%BA%E3%80%8B.md)

**Comment by uinz** [comment]
阅读完后感觉如果 js 有模式匹配的话, 这类问题的处理起来就更加简单和灵活了.
