### ISSUE TITLE
精读《TC39, ECMAScript, and the Future of JavaScript》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#21]
搞清楚 TC39, ECMAScript 之间的关系，以及 js 最近又有什么新动静了。

**Comment by Toona0** [comment]
本期精读文章地址:  https://ponyfoo.com/articles/tc39-ecmascript-proposals-future-of-javascript

**Comment by huxiaoyun** [comment]
占个坑位....哈哈哈哈哈

**Comment by ascoders** [comment]
粗看了一遍，搞明白 TC39，ECMA 与 stage0～4 之间的关系了。后续会整理出来给懒人阅读。

文章末尾提到了对 babel webpack prepack 的积极看法，我也对这些新东西持续关注中，不过本次精读主要会讨论一下全套 stage0～stage4 的提案，纯属个人看法，以后若被打脸，麻烦忘了这期精读。。

**Comment by ascoders** [comment]
废弃的提案：https://github.com/tc39/proposals/blob/master/inactive-proposals.md
stage0: https://github.com/tc39/proposals/blob/master/stage-0-proposals.md
stage1～3: https://github.com/tc39/proposals
stage4 并包含进草案: https://github.com/tc39/proposals/blob/master/finished-proposals.md

**Comment by monkingxue** [comment]
今天看到 **stage0** 又新增一员——**Pattern Matching Syntax**，突然兴奋，这绝对是我最期待的语法之一了。当然也不能高兴太早，按照这期文章中的说法，stage0 还只是 “strawman”，镜中花水中月。

当然从 README.md 中不难发现，模式匹配是有 Object rest 的，而这个语法现在是在 stage3，已经有了 babel 的 Plugin，不太清楚这种依赖性的提案会怎么处理，不过如果要等到 Object rest 并入 master 才会去允许模式匹配提案的进行的话，那未免有点扫兴了（摊手

**Comment by ascoders** [comment]
## Stage 4 大家庭

### [Array.prototype.includes](https://github.com/tc39/Array.prototype.includes/)

```javascript
assert([1, 2, 3].includes(2) === true);
assert([1, 2, 3].includes(4) === false);

assert([1, 2, NaN].includes(NaN) === true);

assert([1, 2, -0].includes(+0) === true);
assert([1, 2, +0].includes(-0) === true);

assert(["a", "b", "c"].includes("a") === true);
assert(["a", "b", "c"].includes("a", 1) === false);
```

这个 api 很方便，没有悬念的进入了草案中。

曾争议过是否使用 Array.prototype.contains，但由于 [不兼容因素](https://esdiscuss.org/topic/having-a-non-enumerable-array-prototype-contains-may-not-be-web-compatible) 而换成了 includes。

### [Exponentiation operator](https://github.com/rwaldron/exponentiation-operator)

```javascript
// x ** y

let squared = 2 ** 2;
// same as: 2 * 2

let cubed = 2 ** 3;
// same as: 2 * 2 * 2
```

列表中进入了 stage4，但其 git 仓库 readme 还停留在 stage3。。

虽然已经有 `Math.pow` 了，但由于其他语言都支持此方式，js 也就支持了。

### [Object.values/Object.entries](https://github.com/tc39/proposal-object-values-entries)

```javascript
Object.values({
	a: 1,
	b: 2,
	c: Symbol(),
}) // [1, 2, Symbol()]

Object.entries({
	a: 1,
	b: 2,
	c: Symbol(),
}) // [["a", 1], ["b", 2], ["c", Symbol()]]
```

也没有什么争议，Object.keys 都有了，获取 values、entries 也是合理的。

TC39 会议中有争辩过为何不返回迭代器，原因挺有意思，因为 Object.keys 返回的是数组，所以这两个 api 还是与老大哥统一吧。

### [String.prototype.padStart / String.prototype.padEnd](https://github.com/tc39/proposal-string-pad-start-end)

```javascript
"foo".padStart(5, "bar") // bafoo
"foo".padEnd(5, "bar") // fooba
```

解决了字符串补齐需求，很棒！

### [Object.getOwnPropertyDescriptors](https://github.com/tc39/proposal-object-getownpropertydescriptors)

```javascript
Object.getOwnPropertyDescriptors({ a: 1})
// { a: {
// 	  configurable: true,
// 	  enumberable: true,
// 	  value: 1,
//	  writable: true
// } }
```

特别是 babel 与 typescript 处理 class property decorator 方式不同的时候（typescript 处理得更成熟一些），会导致 babel 处理装饰器时，成员变量不设置默认值时，configurable 默认为 false，通过这个函数检查变量的配置很方便。

### [Trailing commas in function parameter lists and calls](https://github.com/tc39/proposal-trailing-function-commas)

```javascript
function clownPuppiesEverywhere(
   param1,
   param2, // Next parameter that's added only has to add a new line, not modify this line
 ) { /* ... */ }
```

js 终于原生支持了，以前不支持的时候多加逗号还会报错，需要预编译工具删除最后一个逗号，现在终于名正言顺了。

### [Async functions](https://github.com/tc39/ecmascript-asyncawait)

这个不用多说了，都说好用。

### [Shared memory and atomics](https://github.com/tc39/ecmascript_sharedmem)

这是 ECMAScript 共享内存与 Atomics 的规范，涉及内容非常多，主要涉及到 asm.js，由于对 asm.js 的理解仅处于概念阶段，没有实践过，不做什么评价。

### [Lifting template literal restriction](https://github.com/tc39/proposal-template-literal-revision)

```javascript
styled.div`
  background-color: red;
`
```

`styled.div = text => {}` 就可以处理了，目前使用最多在 styled-components 库里，这种场景还是蛮方便的。

**Comment by jasonslyvia** [comment]
padStart padEnd 早点写入规范说不定就没当年的 leftpad 事件了

**Comment by DanielWLam** [comment]
cool

**Comment by ascoders** [comment]
## Stage 3 大家庭

### [Function.prototype.toString revision](https://github.com/tc39/Function-prototype-toString-revision)

对函数的 toString 规则进行了修改：http://tc39.github.io/Function-prototype-toString-revision/#sec-function.prototype.tostring

当调用内置函数或 `.bind` 后函数，toString 方法会返回 [NativeFunction](http://tc39.github.io/Function-prototype-toString-revision/#prod-NativeFunction)。

### [global](https://github.com/tc39/proposal-global)

为 ECMAScript 规范添加 `global` 变量，同构代码再也不用这么写了：

```javascript
var getGlobal = function () {
	// the only reliable means to get the global object is
	// `Function('return this')()`
	// However, this causes CSP violations in Chrome apps.
	if (typeof self !== 'undefined') { return self; }
	if (typeof window !== 'undefined') { return window; }
	if (typeof global !== 'undefined') { return global; }
	throw new Error('unable to locate global object');
};
```

虽然前端环境与 nodejs 区别很大，但既然提案进入了 stage3，说明大家非常关注 js 整体的生态，只要整体方向良性发展，相信不久将会进入 stage4。

### [Rest/Spread Properties](https://github.com/tc39/proposal-object-rest-spread)

```javascript
let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
x; // 1
y; // 2
z; // { a: 3, b: 4 }
```

不得不说，非常常用，而且 [babel](https://babeljs.io/docs/plugins/transform-object-rest-spread/)，[jsTransform](https://github.com/facebookarchive/jstransform)，[typescript](https://github.com/Microsoft/TypeScript) 均支持，感觉很快会进入 stage4.

**Comment by ascoders** [comment]
## Stage2 大家庭

### [function.sent metaproperty](https://github.com/allenwb/ESideas/blob/master/Generator%20metaproperty.md)

generator 的第一个 `.next` 参数会被抛弃，因为第一次 next 没有对应上任何 `yield`，如下代码就会产生疑惑：

```javascript
function *adder(total=0) {
   let increment=1;
   while (true) {
       switch (request = yield total += increment) {
          case undefined: break;
          case "done": return total;
          default: increment = Number(request);
       }
   }
}

let tally = adder();
tally.next(0.1); // argument will be ignored
tally.next(0.1);
tally.next(0.1);
let last=tally.next("done");
console.log(last.value);  //1.2 instead of 0.3
```

当引入 `function.sent` 后，可以接收来自 next 的传值，**包括初始传值**：

```javascript
function *adder(total=0) {
   let increment=1;
   do {
       switch (request = function.sent){
          case undefined: break;
          case "done": return total;
          default: increment = Number(request);
       }
       yield total += increment;
   } while (true)
}

let tally = adder();
tally.next(0.1); // argument no longer ignored
tally.next(0.1);
tally.next(0.1);
let last=tally.next("done");
console.log(last.value);  //0.3
```

这是个很棒的特性，也不存在语意兼容问题，但 api 还是比较怪，而且自此 yield 接收参数也变得没有意义，况且如今 async await 逐渐成为主流，这种修正没有强烈刚需。而且 yield 的语意本身没有错误，这个提案比较危险。

### [String.prototype.{trimStart,trimEnd}](https://github.com/tc39/proposal-string-left-right-trim)

既然 `padStart` 与 `padEnd` 都进入了 stage4，`trimStart` `trimEnd` 这两个 api 也非常常用，而且从 ES5 将 `String.prototype.trim` 引入了标准来看，这两个非常有望晋升到 stage3。

### [Class Fields](https://github.com/tc39/proposal-class-fields)

```javascript
class Counter extends HTMLElement {
  x = 0;
  #y = 1;
}
```

类成员变量，有了它 js 就完整了。虽然觉得似有变量符号很难看，但成员变量绝对是非常有用的语法，在 react 中已经很常用了：

```javascript
class Todo extends React.Component {
  state = { //.. }
}
```

### [Promise.prototype.finally](https://github.com/tc39/proposal-promise-finally)

就像 `try/catch/finally` 一样，try return 了都能执行 finally，是非常方便的，对 promise 来说也是如此，[bluebird](https://github.com/petkaantonov/bluebird) [Q](https://github.com/kriskowal/q/wiki/API-Reference#promisefinallycallback) 等库已经实现了此功能。
 
但是库实现不足以使其纳入标准，只有当这些需求足够常用和通用时才会考虑。第三方库可能从竞争力角度考虑，多支持一种功能、少些一行代码就是多一份筹码，但语言规范是不能在乎这些的。

### [Class and Property Decorators](http://tc39.github.io/proposal-decorators/)

类级别的装饰器已经进入 stage2 了，但现代前端开发中已经非常常用，很可能会进一步进入 stage3.

如果这个提案被废弃，那么大部分现代 js 代码将面临大量使用不存在语法的窘境。不过乐观的是，目前还找不到更好的装饰器替代方案，而在 python 中也存在装饰器模式可以参考。

**Comment by huxiaoyun** [comment]
重点关注了 stage0 的  cancellation API，  这个特性我感觉会升级的特别快...
###  为啥会出现这个api
1) 取消异步操作，常见以下操作情景：1） 异步方法   2）fetch 请求   3）与浏览器后端交互如 webworker   forked processes   4) 长时间操作  如  动画
2) 和 nodejs  IOT 等其他环境运行的JS API 保持一致

### 关键的类
+ CancellationTokenSource
`class CancellationTokenSource {
  constructor(linkedTokens?: Iterable<CancellationToken>);
  readonly token: CancellationToken;
  cancel(): void;
  close(): void;
}
`
+ CancellationToken
`
class CancellationToken {
    static readonly none: CancellationToken;    // 永远不取消
    static readonly canceled: CancellationToken;   // 已经取消
    readonly cancellationRequested: boolean;  // 标志位，是否取消
    readonly canBeCanceled: boolean;   // 是否可以取消
    throwIfCancellationRequested(): void;
    register(callback: () => void): { unregister(): void; };
}
`
+ CancelError
`
class CancelError extends Error {
    constructor(message?: string);
}
`

### 尝鲜方法和例子

**Comment by ascoders** [comment]
## Stage1 大家庭

### [Date.parse fallback semantics](https://github.com/FaustDeGoethe/proposal-date-time-string-format)

通过字符串格式化日期一直是跨浏览器的痛点，本提案希望通过新增 `Date.parse` 标准完成这个功能。

> "The function first attempts to parse the format of the String according to the rules 
> (including extended years) called out in Date Time String Format (20.3.1.16). If the 
> String does not conform to that format the function may fall back to any 
> implementation-specific heuristics or implementation-specific date formats."

正如提案所说，“如果字符串不满足  ISO 8601 格式，可以返回你想返回的任何值” 这样迷惑开发者是没有任何意义的，这样只会让开发者越来越不相信 js 是跨平台的语言。

这么重要的规范居然才 stage1，必须要顶上去。

### [export * as ns from "mod"; statements](https://github.com/tc39/proposal-export-ns-from)

```javascript
export * as someIdentifier from "someModule";
```

很方便的 api，很多时候希望导出某个模块的全部接口，又不希望命名冲突，可以少写一行 import。


### [export v from "mod"; statements](https://github.com/tc39/proposal-export-default-from)

这个提案与 [export * as ns from "mod"; statements](https://github.com/tc39/proposal-export-ns-from)
 冲突了，感觉 [export * as ns from "mod"; statements](https://github.com/tc39/proposal-export-ns-from)
 提案更清晰一些。

### [Observable](https://github.com/tc39/proposal-observable)

可观察类型可以从 dom 事件、轮询等触发事件中创建监听并订阅：

```javascript
function listen(element, eventName) {
    return new Observable(observer => {
        // Create an event handler which sends data to the sink
        let handler = event => observer.next(event);

        // Attach the event handler
        element.addEventListener(eventName, handler, true);

        // Return a cleanup function which will cancel the event stream
        return () => {
            // Detach the event handler from the element
            element.removeEventListener(eventName, handler, true);
        };
    });
}

// Return an observable of special key down commands
function commandKeys(element) {
    let keyCommands = { "38": "up", "40": "down" };

    return listen(element, "keydown")
        .filter(event => event.keyCode in keyCommands)
        .map(event => keyCommands[event.keyCode])
}

let subscription = commandKeys(inputElement).subscribe({
    next(val) { console.log("Received key command: " + val) },
    error(err) { console.log("Received an error: " + err) },
    complete() { console.log("Stream complete") },
});
```

这个名字和 Object.observe 很像，不过没什么关系。该功能已经被 [RxJS](https://github.com/ReactiveX/RxJS)、[XStream](https://github.com/staltz/xstream) 等库实现。

### [String#matchAll](https://github.com/tc39/String.prototype.matchAll)

目前正则表达式想要匹配全部的语法不够语义化，提案希望通过 `matchAll` 返回迭代器来遍历匹配结果，很赞！

现在匹配全部只能使用 `while ((result = patt.exec(str)) != null)` 这种方式遍历，不优雅。

### [WeakRefs](https://github.com/tc39/proposal-weakrefs)

弱引用，提案地址文档：https://github.com/tc39/proposal-weakrefs/blob/master/specs/Weak%20References%20for%20EcmaScript.pdf

有点像 OC 的弱引用，当对象被释放时，当前持有弱引用的对象也会被 GC 回收，但似乎还没有开始讨论，js 越来越底层了？
