### ISSUE TITLE
精读《用 Babel 创造自定义 JS 语法》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#210]
编译原理是整个编程领域的基座之一，之前的 SQL 智能提示系列已经为语法分析打下了基础，这次我们来读一篇 [用 Babel 创造自定义 JS 语法](https://lihautan.com/creating-custom-javascript-syntax-with-babel/) 的文章，更深入的理解 Babel、理解框架拓展机制，以及持续培养编程细节中的软能力。

---

[精读《用 Babel 创造自定义 JS 语法》](https://github.com/dt-fe/weekly/blob/v2/123.%E7%B2%BE%E8%AF%BB%E3%80%8A%E7%94%A8%20Babel%20%E5%88%9B%E9%80%A0%E8%87%AA%E5%AE%9A%E4%B9%89%20JS%20%E8%AF%AD%E6%B3%95%E3%80%8B.md)

**Comment by missop** [comment]
Test suite failed to run  
Could not locate module @babel/code-frame mapped as:
