### ISSUE TITLE
精读《用 css grid 重新思考布局》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#211]
如果你还没有在项目中使用 css grid，建议和我一起看看本周的精读：：[用 css grid 重新思考布局](https://www.freecodecamp.org/news/css-grid-changes-how-we-can-think-about-structuring-our-content/)，了解一下 css grid 的魔力。

---

[精读《用 css grid 重新思考布局》](https://github.com/dt-fe/weekly/blob/v2/124.%E7%B2%BE%E8%AF%BB%E3%80%8A%E7%94%A8%20css%20grid%20%E9%87%8D%E6%96%B0%E6%80%9D%E8%80%83%E5%B8%83%E5%B1%80%E3%80%8B.md)

**Comment by wxxcarl** [comment]
请问，不是很规范的排列方式，用grid是不是难实现，比如高度的比例并不是刚好整数倍？布局并不是刚好类似table布局？

**Comment by ascoders** [comment]
@wxxcarl 个人感觉，有两种场景不适合 grid：

1. 单维的布局场景。理由是大材小用，反而复杂度会提高。
2. 可变化的布局。理由是布局方式一开始不确定，而 grid 要求区块已经提前规划好了。
