### ISSUE TITLE
精读《Hooks 取数 - swr 源码》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#216]
[swr](https://github.com/zeit/swr) 是一个支持 suspense 的 hooks 取数工具，本周分析它的功能与实现源码。

---

[精读《Hooks 取数 - swr 源码》](https://github.com/dt-fe/weekly/blob/v2/128.%E7%B2%BE%E8%AF%BB%E3%80%8AHooks%20%E5%8F%96%E6%95%B0%20-%20swr%20%E6%BA%90%E7%A0%81%E3%80%8B.md)

**Comment by beidan** [comment]
useSWR(
		{
			url: '',
			params: {
			
			}
		},
		fetcher
	);
为何不支持传递 key 值为对象的情况~

**Comment by beidan** [comment]
使用swr请求之后, 在function中会发现特别多次重新渲染, 对性能是否有影响?

**Comment by ascoders** [comment]
@beidan 应该都是必要的取数，配合代码逻辑实际上不会引发性能问题。

**Comment by beidan** [comment]
@ascoders  请问重试这块源码是怎么实现的?

**Comment by ascoders** [comment]
@beidan try/catch，具体在文章里有写。

**Comment by crimx** [comment]
> 关于 Hooks 取数还是在数据流中取数，你怎么看呢？

非常赞同。Hooks 解决了 class-this 逻辑分散的问题，紧凑的代码更容易分离测试。不再需要委托 stateful 组件或者全局 state 管理库来处理异步逻辑，组件可以重用的东西更丰富了。而且不仅是取数，像异步交互逻辑也可以封装到 hooks 中。

> swr 解决依赖取数的方法还有更好的改进办法吗？

swr 的思路是自行封装一些常见的异步场景，但其实已经有很多成熟的库专门处理异步问题。如 Angular 用的 RxJS，这样的库有丰富成熟的生态可以更灵活应对各种场景（[observable-hooks](https://github.com/crimx/observable-hooks) 可以在 React hooks 中无缝连接 RxJS Observables）。像依赖取数在 RxJS 中按顺序写即可，如果一个结果被多次依赖，只需拆分出单独的流分享。

**Comment by LiuL0703** [comment]
有个疑问，并行取数时当依赖项执行被catch住 onErrorRetry的下次重试取数时间会不会比手动按照依赖项获取耗时呢？

**Comment by ascoders** [comment]
@LiuL0703 肯定会，但不会慢很多。

**Comment by liaokaien** [comment]
> 有个疑问，并行取数时当依赖项执行被catch住 onErrorRetry的下次重试取数时间会不会比手动按照依赖项获取耗时呢？

这里应该作者笔误了， 依赖尚未ready时应该不会触发onErrorRetry机制，而是会在下一次渲染时立即重新取数。 onErrorRetry处理的是fetcher本身抛出的异常

**Comment by ascoders** [comment]
依赖请求这一章之前写的是有问题，现在已经更新到 [正确版本了](精读《Hooks 取数 - swr 源码》
)

> 每次渲染的时候，SWR 会试着执行 key 函数（例如 () => "/api/projects?uid=" + user.id)，如果这个函数抛出异常，那么就意味着它的依赖还没有就绪（user === undefined），SWR 将暂停这个数据的请求。在任一数据完成加载时，由于 setState 触发重渲染，上述 Hooks 会被重选执行一遍（再次检查数据依赖是否就绪）然后对就绪的数据发起新的一轮请求。
