### ISSUE TITLE
精读《unstated 与 unstated-next 源码》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#218]
[unstated](https://github.com/jamiebuilds/unstated) 与 [unstated-next](https://github.com/jamiebuilds/unstated-next) 这两个库都是很有趣的极简状态管理库，同时对比这两个库也非常有趣，欢迎发表你的看法。

---

[精读《unstated 与 unstated-next 源码》](https://github.com/dt-fe/weekly/blob/v2/130.%E7%B2%BE%E8%AF%BB%E3%80%8Aunstated%20%E4%B8%8E%20unstated-next%20%E6%BA%90%E7%A0%81%E3%80%8B.md)

**Comment by ruandao** [comment]
有个疑问，要怎么在 component 外面 修改 unstated-next 的状态，用 useEffect 然后 里面 去subscribe 某个东西吗？

**Comment by tanyplzu** [comment]
> “但这样还是显示使用了 useContext 的 API，并且对 Provider 的封装没有形成固定模式，这就是 usestated-next 要解决的问题。”

老师，这句话怎么理解，相比useContext，到底他解决了什么问题？useContext写起来也很简洁

**Comment by ascoders** [comment]
@tanyplzu 主要是规范的问题，你不能保证大家在 `Provider.value` 传递的一定是 `useCounter` 的返回值，可能有人又包了一个对象之类的。经过封装后，大家就可以形成思维定势，通过 `useContainer` 拿到的一定是 Hooks 返回值，而不是其它什么东西，这个改变看似小，其实是固定了以 Hooks 为第一公民的心智，其实蛮重要的。
