### ISSUE TITLE
精读《CSS Animations vs Web Animations API》

### ISSUE THREAD

**Issue by fanhc019** [dt-fe/weekly#22]
文章地址 https://css-tricks.com/css-animations-vs-web-animations-api/

**Comment by fanhc019** [comment]
WAAPI 为开发者提供的 JavaScript 语法完全可以使用 css 来完成。然而，它们并不是竞争对手的关系。如果你依旧热衷于 css 动画，也可以试试将 css 与 WAAPI 组合起来，或许会有不一样的火花。

**Comment by fanhc019** [comment]
方便大家评论，已经将文章翻译成中文 https://zhuanlan.zhihu.com/p/27867539

**Comment by ascoders** [comment]
完美
