### ISSUE TITLE
精读《正交的 React 组件》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#221]
正交的 React 组件如何设计，好处是什么呢？ [The Benefits of Orthogonal React Components](https://dmitripavlutin.com/orthogonal-react-components/)

---

[精读《正交的 React 组件》](https://github.com/dt-fe/weekly/blob/v2/132.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%AD%A3%E4%BA%A4%E7%9A%84%20React%20%E7%BB%84%E4%BB%B6%E3%80%8B.md)

**Comment by ahonn** [comment]
说白了就是逻辑与视图分离，理想状态下的确是有文章所说的那些好处。
但是如果应用规模一大就会让整个结构变得复杂，而且过早的这种设计可能是一种“过早优化”。感觉开发过程中逐渐的重构正交化会更好。

**Comment by Pengjee** [comment]
但这种分离是理想化的一种分离，实际业务过程中，只要业务逻辑稍微复杂一点，就能很难去完全分离开，多多少少还是会有一些粘连的。

**Comment by crimx** [comment]
> 感觉开发过程中逐渐的重构正交化会更好。

对，结合测试或者 [Storybook](https://storybook.js.org/) 可以在一定程度上约束组件隔离的思考方式。

这个「正交组件」其实就是给「反向依赖」造个新词，其设计跟以前的 render props 很类似，不同的是「正交组件」中所有分支组件无论如何都会执行渲染，而 render props 因为包了一层函数所以性能会好些，缺点是代码不好看。

**Comment by uinz** [comment]
没有理解到  **正交** 的含义.

我从例子理解是 
- 基于 `Hooks` 拆分 `effect`
- 基于 `Suspense` 剥离 `condition`

对复杂组件给出了一个开发范式, 各个组件职责更加清晰.

正交的含义是 当多种情况的产生交点这个时候才 render 核心组件吗?

**Comment by ascoders** [comment]
@uinz 正交本来是数学概念，指的是两个向量垂直关系，也就延伸出完全没有关系（焦点）的含义，所以说两个组件是正交的，意思是修改其中一个组件不会影响另一个。

原文含义是组件逻辑与视图分离，才能提高可维护性，因为职责单一而清晰的组件容器保持与其他组件的正交关系，从而享受到正交带来的好处。
