### ISSUE TITLE
精读《精通 console.log》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#228]
通过 [Mastering JS console.log like a Pro](https://medium.com/javascript-in-plain-english/mastering-js-console-log-like-a-pro-1c634e6393f9) 全面了解一下 console.log，这个最熟悉的陌生人。

---

[精读《精通 console.log》](https://github.com/dt-fe/weekly/blob/v2/138.%E7%B2%BE%E8%AF%BB%E3%80%8A%E7%B2%BE%E9%80%9A%20console.log%E3%80%8B.md)

**Comment by LiuL0703** [comment]
也可以看看这个系列的(DevTools tips)[https://medium.com/@tomsu/devtools-tips-day-1-the-console-dollars-3aa0d93e923c] 24篇每篇都有点小技巧什么的

**Comment by ascoders** [comment]
本周接到一个特殊任务，所以先写另一篇 [精读《当我在分享的时候，我在做什么？》](https://github.com/dt-fe/weekly/issues/229)

**Comment by zclzone** [comment]
> 写得很棒，不过 console.memory  并不是方法

**Comment by ascoders** [comment]
感谢指正，已修复 @zclzone
