### ISSUE TITLE
精读《React Suspense 改变开发方式》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#238]
很多人都用过 React Suspense，但如果你认为它只是配合 React.lazy 实现异步加载的蒙层，就理解的太浅了。实际上，React Suspense 改变了开发规则，要理解这一点，需要作出思想上的改变。

我们结合 [Why React Suspense Will Be a Game Changer](https://medium.com/react-in-depth/why-react-suspense-will-be-a-game-changer-37b40fea71ec) 这篇文章，带你重新认识 React Suspense。

---

[精读《React Suspense 改变开发方式》](https://github.com/dt-fe/weekly/blob/v2/143.%E7%B2%BE%E8%AF%BB%E3%80%8ASuspense%20%E6%94%B9%E5%8F%98%E5%BC%80%E5%8F%91%E6%96%B9%E5%BC%8F%E3%80%8B.md)

**Comment by missop** [comment]
1.suspense是可以代替Loadable吗？
2.子组件只要有请求就会显示fallback？

**Comment by formattedzzz** [comment]
> Suspense 对所有子组件异步都可以作用，因此无论是 React.lazy 还是异步取数，都可以通过 Suspense 进行 Pending。

这点可以说清楚一点吗

**Comment by ascoders** [comment]
@missop 
1. 可以代替。
2. 子组件请求需要进行封装，比如 [useSwr](https://github.com/zeit/swr)，需要支持在 Pending 中抛出 Promise。

**Comment by ascoders** [comment]
@formattedzzz 具体可以看 [useSwr 的 564 行](https://github.com/zeit/swr/blob/master/src/use-swr.ts#L564)。

**Comment by missop** [comment]
好的，明白了

**Comment by missop** [comment]
多谢，明白了

**Comment by youngpj** [comment]
大佬。这个createResource 怎么实现的，react-cache好像现在不能用。

**Comment by xiaorong61** [comment]
> 大佬。这个createResource 怎么实现的，react-cache好像现在不能用。

可以自己写一个，仿照：https://stackoverflow.com/questions/73006253/how-does-react-suspense-know-that-a-promise-has-resolved
