### ISSUE TITLE
文章《12.精读 React 高阶组件》有乱码

### ISSUE THREAD

**Issue by CHWJ** [dt-fe/weekly#24]
文章链接 [在这里](https://github.com/dt-fe/weekly/blob/master/12.%E7%B2%BE%E8%AF%BB%20React%20%E9%AB%98%E9%98%B6%E7%BB%84%E4%BB%B6.md)

[截图在此](http://wx3.sinaimg.cn/large/71cf7958gy1fhp3lp4keej20ox081t8w.jpg)

**Comment by BlackGanglion** [comment]
@CHWJ 已修改，感谢提醒
