### ISSUE TITLE
精读《React Error Boundaries》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#246]
本周精读一篇 React Error Boundaries 介绍文章：[A Simple Guide to Error Boundaries in React](https://alligator.io/react/error-boundaries/)

---

[精读《React Error Boundaries》](https://github.com/dt-fe/weekly/blob/v2/148.%20%E7%B2%BE%E8%AF%BB%E3%80%8AReact%20Error%20Boundaries%E3%80%8B.md)

**Comment by LiuL0703** [comment]
感觉Error  boundaries有点鸡肋

**Comment by ascoders** [comment]
@LiuL0703 可以把原因给出来，方便讨论。

**Comment by lz-lee** [comment]
对于不能捕捉错误的情况是因为 getDerivedStateFromError 执行在 render 阶段，componentDidCatch 执行在 commit 阶段，过了这两个阶段（即一次渲染周期）就无法捕捉了。
