### ISSUE TITLE
精读《React 性能调试》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#247]
继 [精读前端调试技巧](https://github.com/dt-fe/weekly/blob/v2/011.%E7%B2%BE%E8%AF%BB%E5%89%8D%E7%AB%AF%E8%B0%83%E8%AF%95%E6%8A%80%E5%B7%A7.md) 文章后，本周会基于 React 做一次专属性能调试分享，精读的文章为：[Profiling React.js Performance](https://addyosmani.com/blog/profiling-react-js/)

---

[精读《React 性能调试》](https://github.com/dt-fe/weekly/blob/v2/149.%20%E7%B2%BE%E8%AF%BB%E3%80%8AReact%20%E6%80%A7%E8%83%BD%E8%B0%83%E8%AF%95%E3%80%8B.md)

**Comment by lz-lee** [comment]
16.8版本后将 scheduler 单独提出去了，希望出一期精读 scheduler 包相关的。
