### ISSUE TITLE
精读《Deno 1.0 你需要了解的》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#248]
5.13 日 Deno 将发布 1.0 版本，可能有很多人还不了解 Deno 是什么，我们就借着 [Deno 1.0: What you need to know](https://blog.logrocket.com/deno-1-0-what-you-need-to-know/) 这篇文章一起补补课，不论能否用在生产环境，至少先了解一下这个新物种。

---

[精读《Deno 1.0 你需要了解的》](https://github.com/dt-fe/weekly/blob/v2/150.%20%E7%B2%BE%E8%AF%BB%E3%80%8ADeno%201.0%20%E4%BD%A0%E9%9C%80%E8%A6%81%E4%BA%86%E8%A7%A3%E7%9A%84%E3%80%8B.md)

**Comment by missop** [comment]
node_modules没有，那么报错怎么调试
