### ISSUE TITLE
精读《@umijs/use-request》源码

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#249]
[umi request](https://hooks.umijs.org/zh-CN/hooks/async) 很棒，值得读读源码。

---

[精读《@umijs/use-request》源码](https://github.com/dt-fe/weekly/blob/v2/151.%20%E7%B2%BE%E8%AF%BB%E3%80%8A%40umijs%20use-request%E3%80%8B%E6%BA%90%E7%A0%81.md)

**Comment by brickspert** [comment]
瑟瑟发抖。。

**Comment by brickspert** [comment]
大佬，应该是 `@umijs/use-request`

**Comment by ositowang** [comment]
不知道是不是我理解问题，我没有理解他是如何更新这些返回数据的。。
```javascript
return {
    loading: !manual,
    data: initialData,
    error: undefined,
    params: [],
    cancel: noReady('cancel'),
    refresh: noReady('refresh'),
    mutate: noReady('mutate'),

    ...(fetches[newstFetchKey.current] || {}),
    run,
    fetches,
    reset
  } as BaseResult<U, P>;
```
