### ISSUE TITLE
精读《Recoil》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#251]
[Recoil](https://recoiljs.org/) 作为 facebook 出品的数据流框架，本周精读一下其设计思路。

---

[精读《recoil》](https://github.com/dt-fe/weekly/blob/v2/152.%20%E7%B2%BE%E8%AF%BB%E3%80%8Arecoil%E3%80%8B.md)

**Comment by lucifiel0121** [comment]
可能要稍微調整一下用字,
Recoil 應該不算 Facebook 出品

FYI from Dan Abramov at Twitter 
> https://mobile.twitter.com/dan_abramov/status/1262143522959998977
