### ISSUE TITLE
精读《snowpack》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#252]
[snowpack](https://www.snowpack.dev/) snowpack 针对现代浏览器调试提效的构建工具，配合浏览器 [ESM import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) 移除本地不必要的打包工作，将模块化加载工作交给浏览器，大幅提升本地构建效率。

---

[精读《snowpack》](https://github.com/dt-fe/weekly/blob/v2/153.%20%E7%B2%BE%E8%AF%BB%E3%80%8Asnowpack%E3%80%8B.md)

**Comment by zhoukekestar** [comment]
snowpack 和 pikacdn 一起使用更配哈 ~ 欢迎试用：https://github.com/zhoukekestar/snowpack-plugin-import-map

**Comment by random-yang** [comment]
- snowpack 到底有能力将非 esm 的模块转化为 esm 的能力吗，或者说是能力完备吗？

- 你在文中提到的下面这句话，指的是什么意思呢？
> 2. 项目生态存在非 ESM import 模块化包而导致大量适配成本的风险。

---
我在[官网](https://www.snowpack.dev/#import-npm-packages)看到这么一句话：
> *Snowpack lets you import npm packages directly in the browser. Even if a package was published using a legacy format, Snowpack will up-convert the package to ESM before serving it to the browser.*
> 
> Snowpack可让您直接在浏览器中导入npm软件包。即使使用旧格式发布了软件包，Snowpack也会在将其提供给浏览器之前将其上转换为ESM。

**Comment by ascoders** [comment]
@random-yang 你可以用一下，看看是否一个普通项目所有 npm 包都能完美适配。
