### ISSUE TITLE
精读《如何比较 Object 对象》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#258]
你有几种方式对比 Object 对象呢？跟着 [How to Compare Objects in JavaScript](https://dmitripavlutin.com/how-to-compare-objects-in-javascript/) 这篇文章了解一下吧。

Object 对象的比较在不同场景下会使用不同方案，掌握了对比技巧后，还要懂得根据场景选择使用哦。

---

[精读《如何比较 Object 对象》](https://github.com/dt-fe/weekly/blob/v2/157.%20%E7%B2%BE%E8%AF%BB%E3%80%8A%E5%A6%82%E4%BD%95%E6%AF%94%E8%BE%83%20Object%20%E5%AF%B9%E8%B1%A1%E3%80%8B.md)

**Comment by ParseDark** [comment]
em...好像还要加一个函数的对比逻辑....但是比较难啊，如果要比较函数， 就要去调用， 然后比较结果。那如果函数内存在上下文引用或者需要传特定的参数。感觉比较起来会比较难。
```js
deepEqual({a: () => 1}, {a: () => 1}); // false
```

**Comment by ascoders** [comment]
函数引用对比多一些，或者被忽略。
