### ISSUE TITLE
精读《对低代码搭建的理解》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#260]
文章 [对低代码、零代码产品的一些看法](https://zhuanlan.zhihu.com/p/156887528) 引发了业界对低代码搭建的思考，正好我也在阿里集团低代码搭建组织中，且业务涉及以 BI 分析工具、大屏为代表的数据搭建领域，是个典型的业务垂直搭建领域，且这个领域天然具有一套完备的 OLAP 数据模型，我们一直提供零代码数据搭建服务，比如在业界比较知名的 QuickBI。

BI 工具与通用的低代码搭建平台恰恰相反，拥有极低的自由度与极高的分析搭建效率。

随着数据中台业务快速发展，我们的搭建平台承担了阿里经济体越来越多 BU 的搭建诉求，从垂直的 BI 领域逐渐延伸到通用数据产品搭建场景，自然的加入到以通用中后台搭建场景起家的阿里低代码搭建组织中，补充数据搭建领域低代码能力。

脱离业务场景做低代码搭建是业界普遍存在的问题，这是一种前端的自嗨，没有业务场景，不能商业化是无法长久持续的，所以通用搭建平台可以换了一茬又一茬，而那些屹立不倒的搭建平台因为结合了大量业务属性，很多前端同学瞧不上也不想去了解，这样是不对的。

所以我就结合自己的经验，以一个传统 BI 领域向低代码搭建破局的视角，聊聊我眼里的低代码搭建。

---

[精读《对低代码搭建的理解》](https://github.com/dt-fe/weekly/blob/v2/159.%20%E7%B2%BE%E8%AF%BB%E3%80%8A%E5%AF%B9%E4%BD%8E%E4%BB%A3%E7%A0%81%E6%90%AD%E5%BB%BA%E7%9A%84%E7%90%86%E8%A7%A3%E3%80%8B.md)

**Comment by xilixjd** [comment]
低代码其实不应强调搭建，不应强调可视化，叔叔的文章就完全不强调这两点

**Comment by 07akioni** [comment]
不搭建不可视化不适合把这个事情讲大

**Comment by ascoders** [comment]
低代码搭建就是因为可视化+代码才提升了研发效率，纯代码提效那就是研发框架的事了。

**Comment by taowen** [comment]
每个人都有自己心目中的最重要的优化手段，没必要说服谁，能达到目标就是好的手段。我拉了一个从业者的微信群，欢迎进来交流 https://github.com/taowen/awesome-lowcode

**Comment by shockw4ver** [comment]
猜想，如果专门有一套用于深度代码定制的抽象为 LowCode 模型提供扩展，映射到 LowCode 中的各个单元，类似于用 hook 进行插入那种，可能会使 LowCode 的适应能力更强一些；而扩展自身又可以封装再复用的话，也许能有生态化的效应。

**Comment by 07akioni** [comment]
一个东西好用和有价值不会是因为概念听起来 fancy 就能成立，在发展前对结果有一个在*现实*中如何使用的明确预期能尽量保证产品实现不是自嗨。

>  脱离业务场景做低代码搭建是业界普遍存在的问题，这是一种前端的自嗨，没有业务场景，不能商业化是无法长久持续的，所以通用搭建平台可以换了一茬又一茬，而那些屹立不倒的搭建平台因为结合了大量业务属性，很多前端同学瞧不上也不想去了解，这样是不对的。

这个说的很对

**Comment by Channely** [comment]
> 猜想，如果专门有一套用于深度代码定制的抽象为 LowCode 模型提供扩展，映射到 LowCode 中的各个单元，类似于用 hook 进行插入那种，可能会使 LowCode 的适应能力更强一些；而扩展自身又可以封装再复用的话，也许能有生态化的效应。

一是，这种一一映射，基本等价于**再造一门语言**（大概率会降低效率）；拓展约等于DSL；
二是，基于低代码平台在研发实践中的应用情况来看，对于追着这个概念并念念不忘的人，他们的**初心**更倾向于“AI编程”，一点都**不想介入编程的（思维）领域**，哪怕是图形化的编程。

**Comment by shockw4ver** [comment]
> > 猜想，如果专门有一套用于深度代码定制的抽象为 LowCode 模型提供扩展，映射到 LowCode 中的各个单元，类似于用 hook 进行插入那种，可能会使 LowCode 的适应能力更强一些；而扩展自身又可以封装再复用的话，也许能有生态化的效应。
> 
> 一是，这种一一映射，基本等价于**再造一门语言**（大概率会降低效率）；拓展约等于DSL；
> 二是，基于低代码平台在研发实践中的应用情况来看，对于追着这个概念并念念不忘的人，他们的**初心**更倾向于“AI编程”，一点都**不想介入编程的（思维）领域**，哪怕是图形化的编程。

第一点的话，其实我想表达的是通过类似于 protobuf 这种方式进行配置上的抽象，那么不同平台的的开发者实际上是去根据这个抽象在各自平台上来实现，这样就分成了生产者（开发扩展）和消费者（LowCode 应用），大概就是一种市场形式。

第二点来讲，LowCode 其实还有一个重要的特点就是将基础或者叫样板部分工作的关注点与实际业务的关注点分开，比如早期的 Dreamwaver，它可以解决一些实际业务问题（像用 <map> 做的大量淘宝详情页面），但是其逻辑编排和出码能力也限制了它继续的发展，毕竟这种大教堂式的解决方案很难满足浪潮般来临的各种需求。
AI 编程这一点我也赞同，但若要**足够的 AI**，足够的业务模型也很重要，而扩展的可用性可能就是为各种业务模型提供的一个参考因素。毕竟技术是驱动业务发展的动力源之一，思考基于技术的概念时如果完全脱离了技术，很容易就陷入空中楼阁，迟迟不能落地

**Comment by taowen** [comment]
protobuf 这样的配置用来描述行为是非常笨拙的。你想想 webpack 的配置文件，是一个纯配置。但是你要控制那么多的行为，所以就要加那么多的 option 参数。option加多了之后，多少人看得懂这样的 webpack 配置文件呢？样板代码和业务代码没有一个清晰的边界，今天看起来是样板代码，明天需求来了之后就变成了业务。最重要的还是包管理，把代码按照变更频率分出来，进行依赖管理。天天变的代码就是业务，变得少的就是样板代码。

**Comment by shockw4ver** [comment]
害，只是举个一对多的例，但 protobuf 描述行为，但要做抽象当然不能照本宣科其他领域的实践，重要的还是有一套渐进的规则。
像 webpack，尽管产出可能复杂，但其规则总的也就是引擎+插件嘛，而各式各样的 options 不正是为了满足各种各样的需求，这也侧面印证了在实际的业务需求满足过程，往往就是一个添砖加瓦的过程。当整个生态达到了一定的平衡点时，各种需求都摸得比较清后，自然就会有更”聪明“的实践逐步产生，譬如 vite、roma 这些”新成员“。
当然，这只是构想...  LowCode 不会像 webpack 那么容易讨好，还得等领域里的 pioneer 们开路...

**Comment by 07akioni** [comment]
> 害，只是举个一对多的例，但使用 protobuf 描述行为也不一定就笨拙，毕竟有这么句“**接口描述的应当是行为，而非数据**”嘛，但要做抽象当然不能照本宣科其他领域的实践，重要的还是有一套渐进的规则。
> 像 webpack，尽管产出可能复杂，但其规则总的也就是引擎+插件嘛，而各式各样的 options 不正是为了满足各种各样的需求，这也侧面印证了在实际的业务需求满足过程，往往就是一个添砖加瓦的过程。当整个生态达到了一定的平衡点时，各种需求都摸得比较清后，自然就会有更”聪明“的实践逐步产生，譬如 vite、roma 这些”新成员“。
> 当然，这只是构想... LowCode 不会像 webpack 那么容易讨好，还得等领域里的 pioneer 们开路...

Webpack 虽然用起来很蛋疼，但是 `it simply works`，难用也无法掩盖它的价值。相比之下 low code 还没有找到一个足够 `it simply works` 的场景。
