### ISSUE TITLE
精读《函数缓存》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#261]
在函数调用场景下，对性能消耗较大的函数进行缓存是重要的性能优化手段。

精读文章：https://whatthefork.is/memoization

---

[精读《函数缓存》](https://github.com/dt-fe/weekly/blob/v2/160.%20%E7%B2%BE%E8%AF%BB%E3%80%8A%E5%87%BD%E6%95%B0%E7%BC%93%E5%AD%98%E3%80%8B.md)

**Comment by 0xAC7** [comment]
函数本身也是对象，所以也可以直接将缓存存放到自身。

**Comment by 07akioni** [comment]
> 函数本身也是对象，所以也可以直接将缓存存放到自身。

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee

`arguments.callee` 已经被废弃了，有啥新办法能让函数自己访问到自己么
