### ISSUE TITLE
下载zip文件提示检测到病毒

### ISSUE THREAD

**Issue by SZP1206** [dt-fe/weekly#263]
具体情况如下图：
![Snipaste_2020-08-13_10-26-02](https://user-images.githubusercontent.com/43406070/90087513-8e6ec380-dd4f-11ea-9166-a7cf7dd84be1.png)
![Snipaste_2020-08-13_10-25-41](https://user-images.githubusercontent.com/43406070/90087514-9169b400-dd4f-11ea-9859-d7d5fa4e4e85.png)

请问是误报吗？谢谢

**Comment by atian25** [comment]
搞笑。。。

**Comment by think2011** [comment]
哈哈哈 说不定是挖矿关键字被误报了

**Comment by dancerphil** [comment]
哈哈哈，不下载即可

**Comment by ascoders** [comment]
直接在线看吧，都是文字也没有攻击性，应该是误报。
