### ISSUE TITLE
精读《数据搭建引擎 bi-designer API-设计器》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#267]
bi-designer 是数据中台团队自研的数据产品搭建引擎，基于其研发的 BI 工具有阿里内最大数据分析平台，以及阿里云上的 QuickBI，由于引擎内核不涉及任何商业机密，因此我可以做一些分享甚至开源，但在这之前，我会先分享一下其 API 设计，也顺便征求一下大家的意见，毕竟 API 的讨论是比较容易的。

本部分分两篇，分别是 《API-设计器》与 《API-组件》，本期先介绍一下设计器的 API，看看这个基于 React 实现的引擎整体是怎么用的。

---

[精读《数据搭建引擎 bi-designer API-设计器》](https://github.com/dt-fe/weekly/blob/v2/164.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%95%B0%E6%8D%AE%E6%90%AD%E5%BB%BA%E5%BC%95%E6%93%8E%20bi-designer%20API-%E8%AE%BE%E8%AE%A1%E5%99%A8%E3%80%8B.md)

**Comment by zhangwilling** [comment]
期待

**Comment by boqiaok** [comment]
通过Designer, 划分成component,  render, setting. bi设计器或者可视化装修的编辑器都可以按bi-designer搭建
bi-designer 有抽象component拖拽的逻辑吗?

**Comment by zhouping3** [comment]
1.shouldDeleteComponents这个地方的代码demo有码误
2.多了一层page的schema解析协议层，对页面渲染性能影响大吗，会不会出现一些全局状态导致的一些不必要渲染
3.期待+1，开源的计划有大致的时间带你吗

**Comment by zhouping3** [comment]
1.shouldDeleteComponents这个地方的代码demo有码误
2.多了一层page的schema解析协议层，对页面渲染性能影响大吗，会不会出现一些全局状态导致的一些不必要渲染
3.期待+1，预计啥时候开源呢，嘻嘻

**Comment by ascoders** [comment]
@zhouping3 
1. 感谢反馈，已修复。
2. 性能影响不大，目前还没遇到引擎导致的性能瓶颈，都是业务层复杂组件的性能问题。
3. 等 QuickBI 卖的再好一点再考虑开源吧，哈哈。

**Comment by petergeng** [comment]
期待开源
