### ISSUE TITLE
精读《BI 搭建 - 筛选条件》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#270]
本周介绍 BI 搭建工具之筛选条件设计，我们分享在 BI 领域探索出的良好设计模式，希望能帮助到其他也在研发 BI 工具的前端同学，当然内容也欢迎指正。

---

[精读《BI 搭建 - 筛选条件》](https://github.com/dt-fe/weekly/blob/v2/166.%E7%B2%BE%E8%AF%BB%E3%80%8ABI%20%E6%90%AD%E5%BB%BA%20-%20%E7%AD%9B%E9%80%89%E6%9D%A1%E4%BB%B6%E3%80%8B.md)

**Comment by blingxing** [comment]
你好，想问下可以看到代码实现么

**Comment by ascoders** [comment]
源码暂不开放，读懂原理就可以了，我即使放了源码你也不一定会直接用，不是吗～

**Comment by blingxing** [comment]
嗯嗯，方案很优秀，赞

**Comment by ecantsiDehToG** [comment]
这方面还有其他学习资料能推荐吗

**Comment by ascoders** [comment]
> 这方面还有其他学习资料能推荐吗

目前都是一边实践一边总结，有机会我会出一套完整系列。如果其他社区资料有 BI 搭建相关经验文章，环境发出来一起交流学习。

**Comment by TheBeard30** [comment]
学习了 👍👍

**Comment by Echohzy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已收到。
