### ISSUE TITLE
精读《设计模式 - Abstract Factory 抽象工厂》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#271]
本周开始进入设计模式系列，网上有很多通俗易懂的文章，那我就以更通俗的例子说明设计模式要解决的问题，用 js 写 demo，希望看一遍就懂。

---

[精读《设计模式 - Abstract Factory 抽象工厂》](https://github.com/dt-fe/weekly/blob/v2/167.%E7%B2%BE%E8%AF%BB%E3%80%8A%E7%B2%BE%E8%AF%BB%E3%80%8A%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%20-%20Abstract%20Factory%20%E6%8A%BD%E8%B1%A1%E5%B7%A5%E5%8E%82%E3%80%8B%E3%80%8B.md)

**Comment by sluk3r** [comment]
这个方式记录和讨论不错， 赞
