### ISSUE TITLE
精读《设计模式 - Builder 生成器》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#273]
设计模式属于能看懂，又很容易忘记的知识，为了方便设计模式应用于日常项目中，精读会增加一些配图解释，希望在读完设计模式后，以后再次翻阅文章时，通过图就可以快速回忆起内容。

上次的抽象工厂我们举了三个例子：汽车工厂、迷宫游戏、事件联动，我觉得这种例子也很利于理解枯燥的设计模式，后面的文章都会用类似的手法书写。

---

[精读《设计模式 - Builder 生成器》](https://github.com/dt-fe/weekly/blob/v2/168.%E7%B2%BE%E8%AF%BB%E3%80%8A%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%20-%20Builder%20%E7%94%9F%E6%88%90%E5%99%A8%E3%80%8B.md)

**Comment by ositowang** [comment]
挖个坟，最近才又有时间看了，按照示例里的代码的话，那么如果我要再增加一个concreatebuilder, 我们就得同时修改director 和 添加一个新的concreatebuilder嘛，不知道是否我理解有误。
`
class Director {
  create(concreteBuilder: ConcreteBuilder) {
    // 创建了一些零件
    concreteBuilder.buildA();
    concreteBuilder.buildB();

    // 校验参数已经生成实例
    return concreteBuilder.build();
  },
  createCabin(builder:concreateBuilder){
     buildA,
     buildB,
     buildC,
    return builder.build()
  }
}

class CabinBuilder {
  public buildA() {
    // 创建房屋
    // this.xxx = xxx
  }

  public buildB() {
    // 刷油漆
  }
public buildC(){
// add roof
}

  public build() {
    // 最终创建实例
    return new House(/* ..一堆参数 this.xxx.. */);
  }
}
`

**Comment by ascoders** [comment]
新增一个 Builder 一般不用新增 Director：

```typescript
const director = new Director();
const houseBuilder = HouseBuilder();
const house = director.create(houseBuilder);
const carBuilder = CarBuilder();
const car = director.create(carBuilder);
```

**Comment by levidcd** [comment]
`const builder = HouseBuilder()` 是不是少了new
