### ISSUE TITLE
精读《设计模式 - Singleton 单例模式》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#278]
单例模式似乎是最容易理解的，但想要透彻理解，还是要系统的学习。

---

[精读《设计模式 - Singleton 单例模式》](https://github.com/dt-fe/weekly/blob/v2/171.%E7%B2%BE%E8%AF%BB%E3%80%8A%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%20-%20Singleton%20%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F%E3%80%8B.md)

**Comment by Salted-Fish-Swimming** [comment]
为什么全局变量会污染全局？class 的名字不一样也污染了全局？

**Comment by ascoders** [comment]
> 为什么全局变量会污染全局？class 的名字不一样也污染了全局？

也是，单例模式对前端可能没啥用，因为 es module 只要 export 默认都是单例的。

**Comment by XuesenXu** [comment]
```ts
class Ball {
  private _instance = undefined;

  private constructor () {

  }

  public static getInstance = () => {
    if (this._instance === undefined) {
      this._instance = new Ball()
    }

    return this._instance
  }
}

const ball = Ball.getInstance();
```

这个例子中`getInstance`方法中的`_instance`不会报错吗？
