### ISSUE TITLE
精读《设计模式 - Proxy 代理模式》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#291]
代理模式是指利用访问代理的方式，代替访问原始对象。这种模式有很多使用场景，比如对已有对象做增强、做按需初始化等等。

---

[精读《设计模式 - Proxy 代理模式》](https://github.com/dt-fe/weekly/blob/v2/178.%E7%B2%BE%E8%AF%BB%E3%80%8A%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%20-%20Proxy%20%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F%E3%80%8B.md)

**Comment by CommanderXL** [comment]
这2天阅读了下  `@vue/composition-api` 的代码了解了下 vue 组合式的 api 对于 `vue2.x` 的兼容，里面也是使用代理模式的场景非常多。

例如 `reactive`、`ref` 等响应式的 api，是在原本已经改造后的响应式数据的基础上再做一层代理，既保证了通过响应式 api 改造后数据的响应特性，同时还满足了原本所具备的双向数据绑定的机制。
