### ISSUE TITLE
有计划出web perfomance相关的系列嘛？

### ISSUE THREAD

**Issue by ositowang** [dt-fe/weekly#294]
最近有在研究这方面的材料，感觉找到的资料都东一块西一块的，说的也都不够深度。不知道周刊有没有出一个系列的打算

**Comment by qiwang97** [comment]
再加上埋点和可视化？

**Comment by ascoders** [comment]
设计模式系列结束后会考虑的，我考虑让团队专门做性能优化同学来写一些文章。

**Comment by ascoders** [comment]
写设计模式时，发现大家共鸣明显减少了，可是技术越做到后面，设计模式会越重要，随着工作年限的增长，你会越来越明白这个事实。

**Comment by ositowang** [comment]
其实没有，就是过节加上一个一个模式其实光看文章效果不大，还是得去啃你给的例子源码，这个时间跨度就很长了，而且还经常啃不明白，我个人还是很受用的。

**Comment by qiwang97** [comment]
> 写设计模式时，发现大家共鸣明显减少了，可是技术越做到后面，设计模式会越重要，随着工作年限的增长，你会越来越明白这个事实。

我现在就明显感觉到设计模式的重要了。很多问题都能解决，但是了解过一些设计模式之后，就发现之前的写法很粗糙，很麻烦
