### ISSUE TITLE
精读《设计模式 - Iterator 迭代器模式》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#298]
迭代器模式是遍历集合对象的通用方法，好处是遍历者不需要了解集合对象的内部结构，符合迪米特法则。

---

[精读《设计模式 - Iterator 迭代器模式》](https://github.com/dt-fe/weekly/blob/v2/182.%E7%B2%BE%E8%AF%BB%E3%80%8A%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%20-%20Iterator%20%E8%BF%AD%E4%BB%A3%E5%99%A8%E6%A8%A1%E5%BC%8F%E3%80%8B.md)

**Comment by yaowencurry** [comment]
` 
 next() {
    return this.list.values[this.list.index] // 注意边界情况，这里就不展开
    this.list.index++
  }
`

这里是不是写错了，都`return`了，后面的`this.list.index++`应该没用了吧。
