### ISSUE TITLE
精读《设计模式 - Mediator 中介者模式》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#299]
中介者模式很常见，通过第三方中介引用子模块，从而避免子模块之间的相互引用，不仅可以解耦，甚至可以解决循环依赖的 “难题”。

---

[精读《设计模式 - Mediator 中介者模式》](https://github.com/dt-fe/weekly/blob/v2/183.%E7%B2%BE%E8%AF%BB%E3%80%8A%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%20-%20Mediator%20%E4%B8%AD%E4%BB%8B%E8%80%85%E6%A8%A1%E5%BC%8F%E3%80%8B.md)

**Comment by xusanduo08** [comment]
将数据认作中介总感觉有些别扭。实际开发中操作的是数据，中间通过UI工具生成页面，数据-> UI工具 -> 页面，所以中介为啥不是UI工具呢？

**Comment by ascoders** [comment]
@xusanduo08 站在开发者角度，数据驱动是中介者模式最有力的证明。不知道你提的 UI 工具是哪一类的，如何使制作页面的过程变得耦合松散呢？
我能想到的比如搭建系统，要做到耦合松散本质上还是数据驱动，所以还是以数据 -> 代码的例子更本质一些。

**Comment by xusanduo08** [comment]
大概明白你的意思：从开发者角度，在开发者到web页面之间，数据是一个中介，是否这样理解？
