### ISSUE TITLE
精读《设计模式 - Memento 备忘录模式》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#301]
备忘录模式是一种捕获对象内部状态的设计模式。

在 undo、redo 场景下，设计器只能捕获与还原受控状态（对组件来说则是外部状态），而无法还原组件内部状态，备忘录模式可以优雅的解决这个问题。

---

[精读《设计模式 - Memoto 备忘录模式》](https://github.com/dt-fe/weekly/blob/v2/184.%E7%B2%BE%E8%AF%BB%E3%80%8A%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%20-%20Memoto%20%E5%A4%87%E5%BF%98%E5%BD%95%E6%A8%A1%E5%BC%8F%E3%80%8B.md)

**Comment by 791106912** [comment]
感觉备忘录模式，有点像storage的getItem、setItem。不知道理解的对不对。
