### ISSUE TITLE
nestjs 有demo吗？

### ISSUE THREAD

**Issue by raineliu** [dt-fe/weekly#32]

**Comment by ascoders** [comment]
可以看官方推荐的 typeorm demo：https://github.com/zachgrayio/nest-typeorm-example

**Comment by raineliu** [comment]
在这个基础上怎么写页面，创建views目录，然后把页面文件放这里面？

**Comment by ascoders** [comment]
一般是前后端分离的，这个可以做纯服务。页面只需要一个路由返回 html 即可。

**Comment by raineliu** [comment]
我写了一个登录页，但是怎么把前端和后端搭建起来呢，用ngix吗？

**Comment by ascoders** [comment]
可以不用 nginx。

建议只询问 nestjs 特色相关问题，环境搭建等基础问题可以 google。

**Comment by DivXPro** [comment]
说实话 typeorm 用起来还是有很多不足，最佳再试者用nestjs重构一个项目 还是用sequelize算了 只不过定义model不能用装饰器。
