### ISSUE TITLE
精读《V8 引擎特性带来的的 JS 性能变化》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#33]
本周精读文章是：[V8 引擎特性带来的的 JS 性能变化
](https://www.nearform.com/blog/node-js-is-getting-a-new-v8-with-turbofan/)

**Comment by ascoders** [comment]
## try catch 对性能的影响忽略不计

try catch 非常有用，特别在 node 端更是一个常规操作。前端框架也越来越多采用了异常捕获的方式，结合 async await 让代码组织得更加优雅。react mixins 也喜欢 try 住 render 方法，包括 16 版本自动 try 住了所有 render，try catch 可谓无处不在。

node 8 版本之后 try 内部函数性能损耗可以忽略不计。

但是当前版本仍然存在安全隐患，将这里的代码拷贝到 chrome 控制台，当前页面会进入无限死循环：https://gist.github.com/mcollina/a40c6c3820287a474e9943406385c738。

**Comment by mynane** [comment]
有个疑问， 这个精读是所有人都可以参与， 还是说指定人才能回答？

**Comment by ascoders** [comment]
@mynane 所有人都可以参加

**Comment by ascoders** [comment]
## 解决 delete 性能问题

js 正在变得越来越简单，该 delete 的地方也不会犹豫是否写成 undefined，以提升性能为代价降低代码可读性了。

## arguments 转数组性能已不是问题

在 node8.3 版本及以上，该使用拓展运算符获取参数，不但没有性能问题，可读性也大大提高，结合 ts 时也能得到类型支持。

## bind 对性能影响可以忽略

但是在 react 中副作用仍需警惕。由于 ui 组件复用次数在大部分场景及其有限，强烈推荐使用箭头函数书写成员函数（在我的另一篇精读 [This 带来的困惑](https://github.com/dt-fe/weekly/blob/master/13.This%20%E5%B8%A6%E6%9D%A5%E7%9A%84%E5%9B%B0%E6%83%91.md#4-总结) 有详细介绍），而且在 node8 中，箭头函数的性能是最好的。

**Comment by linhuiw** [comment]
翻到本次精读的译文贴出来:
https://zhuanlan.zhihu.com/p/28225985

**Comment by ascoders** [comment]
## 函数调用对性能影响越来越小

对函数调用优化的越来越好，不需要过于担心注释与空白、函数间调用对性能的影响.

## 32 64 位数字计算性能

node8 对超长数字计算性能还是较低，大概是 32 位数字性能的 2/3，所以尽量用字符串处理大数。

## 遍历 object

基本用法有 `for in` `Object.keys` `Object.values`. 在 node8 中，`for in` 将变得更慢，但任然比其他两种方法快，所以，尽早取消不必要的优化。

## 创建对象

创建对象速度在 node8 得到极大提升，似乎是面向对象编程的福音。

## 多态函数的性能问题

当函数或者对象存在多种类型参数时，在 node8 中性能没什么优化，但单态函数性能大幅提升。所以尽量让对象内部属性单态是比较有用的，比如尽量不要对字符串数组 `push` 一个数字。
