### ISSUE TITLE
精读《null >= 0?》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#36]
本期精读的文章是：[null >= 0](https://blog.campvanilla.com/javascript-the-curious-case-of-null-0-7b131644e274)

看来大于等于号在 js 的执行逻辑并不符合直觉。

**Comment by linhuiw** [comment]
按文中说的,  
```
if null < 0 is false, then null >= 0 is true; 
```
那可以理解 为什么 null >= 0 了. 
同理 {} >= {} 也是 true; 
```
{} < {} // false
{} >= {} // true
```

可是那为啥
```
null == {} // false
null < {} // false
null >= {} //false
```

![image](https://user-images.githubusercontent.com/722603/30726959-b0d726b6-9f80-11e7-9f84-404a79b2313c.png)

**Comment by ascoders** [comment]
@linhuiw js 作判断时，首先在两个值上调用 ToPrimitive coercion，如果两个调用的结果都不是 string，就会对两个值进行 ToNumber 强转为 number，然后进行数值比较。

> if null < 0 is false, then null >= 0 is true; 

```javascript
null >= 0 // is null < 0 ?
+null < 0 // => 0 < 0 => false, so null >= 0 is true
```

让我们看一下为什么 `null >= [] === true`?

```
null >= [] // is null < []? => 将右边转换为 "0" => 将 null 转换为 0 => 将 "0" 转换为 0 => 0 < 0 显然是 false
// so null >= [] === true
```

再看看 `null >= [1]` 呢？答案是 false，最终会进行 `0 < 1` 的比较，因此反过来就是 false。

至于下面的情况：

> null >= {} is false;

像 `[]` `''` `'0'` `false` 强转 `ToNumber` 后值为 0，而 `Number({})` 的结果为 `NaN`。

```javascript
null >= {} // is null < {} => is null < NaN => is 0 < NaN === false
// so null >= {} === true?
```

正常来看 `null >= {}` 结果应该是 true，但结果却是 false。我估计因为 NaN 在 js 中是个特殊的存在，所以直接判定为 false，而没有进行反转判断。

**Comment by ascoders** [comment]
当比较两边类型不同时，先做类型转换，当类型相同时，如果是 >= 判断，会转成 < 判断。而 NaN 会无视类型转换直接给出 false 结果，因此很可能跳过了 < 判断。

**Comment by Mrcooder** [comment]
@ascoders  说的不错，但是有点问题，[] 是转换成 "" 而不是 "0"；对于允许隐式转换的比较操作，只要一个操作数是 NaN，那么这个表达式一定返回 false。

这是隐式转换表

![](https://i.loli.net/2017/09/22/59c4cb1b83d4c.png)

**Comment by realwugang** [comment]
学习了。
