### ISSUE TITLE
精读《W3C发布加密媒体扩展（Encrypted Media Extensions，EME）正式推荐标准》

### ISSUE THREAD

**Issue by TingGe** [dt-fe/weekly#37]
精读文章地址: 
- [W3C 发布 EME 标准，EFF 退出 W3C](https://juejin.im/post/59c0a93af265da06456d69d9)
- [W3C发布加密媒体扩展（Encrypted Media Extensions，EME）正式推荐标准](http://www.chinaw3c.org/2017-09-pressrelease-eme-recommendation.html)
- [An open letter to the W3C Director, CEO, team and membership](https://www.eff.org/deeplinks/2017/09/open-letter-w3c-director-ceo-team-and-membership)
- 还有篇2013年的老文章 [危险的Encrypted Media Extensions(EME，加密媒体扩展协议)标准初稿即将发布](https://bitinn.net/10281/)

 2017年9月18日， “ W3C 发布 EME 标准，EFF 退出 W3C” 。我们今天来聊聊，这个有争议的  EME 到底是什么？和 DRM 有什么关系？它会对 Web 未来产生什么样的影响？

**Comment by xekri** [comment]
提供一个hacker news上的热门讨论帖以供参考：https://news.ycombinator.com/item?id=15278883


On 2017年9月22日 at 上午2:25:39, Kevin (notifications@github.com<mailto:notifications@github.com>) wrote:

精读文章地址:

  *   W3C 发布 EME 标准，EFF 退出 W3C<https://juejin.im/post/59c0a93af265da06456d69d9>
  *   W3C发布加密媒体扩展（Encrypted Media Extensions，EME）正式推荐标准<http://www.chinaw3c.org/2017-09-pressrelease-eme-recommendation.html>
  *   An open letter to the W3C Director, CEO, team and membership<https://www.eff.org/deeplinks/2017/09/open-letter-w3c-director-ceo-team-and-membership>
  *   还有篇2013年的老文章 危险的Encrypted Media Extensions(EME，加密媒体扩展协议)标准初稿即将发布<https://bitinn.net/10281/>

2017年9月18日， “ W3C 发布 EME 标准，EFF 退出 W3C” 。我们今天来聊聊，这个有争议的 EME 到底是什么？和 DRM 有什么关系？它会对 Web 未来产生什么样的影响？
