### ISSUE TITLE
精读《JS 中的内存管理》

### ISSUE THREAD

**Issue by linhuiw** [dt-fe/weekly#40]
文章地址：https://blog.sessionstack.com/how-javascript-works-memory-management-how-to-handle-4-common-memory-leaks-3f28b94cfbec

学习一下处理常见的内存泄露情况, 在写代码的时候稍微注意一下, 防范内存泄露问题. 
PS: sessionstack出品的几篇 [How JavaScript works](https://blog.sessionstack.com/tagged/tutorial) 系列文章都挺不错的.

**Comment by ascoders** [comment]
C++ 作者说过：C 很容易让你朝自己的脚开枪，尽管在 C++ 中，这么做困难了，但只要不注意，就可能崩掉整条腿。

JS 这类高级语言，隐藏了内存管理功能。但无论开发人员是否注意，内存管理都在那，所有编程语言最终要与操作系统打交道，在内存大小固定的硬件上工作。不幸的是，即使不考虑垃圾回收对性能的影响，2017 年最新的垃圾回收算法，也无法智能回收所有极端的情况。

唯有程序员自己才知道何时进行垃圾回收，而 JS 由于没有暴露显示内存管理接口，导致触发垃圾回收的代码看起来像“垃圾”，或者优化垃圾回收的代码段看起来不优雅、甚至不可读。

所以在 JS 这类高级语言中，有必要掌握基础内存分配原理，在对内存敏感的场景，比如 nodejs 代码做严格检查与优化。谨慎使用 dom 操作、主动删除没有业务意义的变量、避免提前优化、过度优化，在保证代码可读性的前提下，利用性能监控工具，通过调用栈定位问题代码。

**Comment by hardfist** [comment]
第一段代码等价于
```
componentWillMount() {
    return new Promise(resolve => {
      this.setState({
        a: 1
      })
      resolve();
    })
  }
```
React 不会对componentWillMount进行await调用，new Promise(resolver)里的resolver是同步执行的，所以实际上这段代码就等价于this.setState({a:1})，componentWillMount中同步调用setState不会触发rerender。
而第二段代码等价于
```
 componentWillMount() {
    return new Promise(resolve => {
      return Promise.resolve().then(() => {
        this.setState({
          a: 1
        })
      })
    })
  }
```
这里的setState是在内部Promise的then回调里执行的，所以是异步执行的，所以会触发rerender。
所以两者的区别只是在于在componentWillMount里是同步执行还是异步执行的而已。

**Comment by liSong5713** [comment]
这个代码通过目前的chrome 72来跑没有发生内存泄漏，是在低版本中有问题吧
