### ISSUE TITLE
精读《React Router4.0 进阶概念》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#43]
本期文章：https://blog.logrocket.com/advanced-react-router-concepts-code-splitting-animated-transitions-scroll-restoration-recursive-17096c0cf9db

React Router4.0 和 3.x 相差还是蛮大的，不，应该是相比所有语言的路由系统，相差很大。就算你精通了 3.x，还是有必要了解了解 4.0 的特性，看看这个不一样的 Router 带给我们怎么样的开发体验？

**Comment by liubin915249126** [comment]
有没有react-loadable简单的例子供参考下，这边路由切割代码时报错了

**Comment by ascoders** [comment]
@liubin915249126 文档的 [example](https://github.com/thejameskyle/react-loadable/blob/master/example) 文件夹就有例子。
