### ISSUE TITLE
精读《React 代码整洁之道》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#46]
本期精读的文章：http://americanexpress.io/clean-code-dirty-code/

之前写了一篇 [API设计规则](https://github.com/dt-fe/weekly/blob/master/23.%E7%B2%BE%E8%AF%BB%E3%80%8AAPI%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99%E3%80%8B.md) 的文章，这次我们看一篇关于 React 编码规范相关的文章。

编程语言具有最大的灵活性，但编程又是一项具有艺术色彩的行为，有人成了代码的搬运工，也有人对代码仔细打磨。

**Comment by chaosJS** [comment]
请问，https://github.com/dt-fe/weekly/blob/master/34.%E7%B2%BE%E8%AF%BB%E3%80%8AReact%20%E4%BB%A3%E7%A0%81%E6%95%B4%E6%B4%81%E4%B9%8B%E9%81%93%E3%80%8B.md
这一期最后部分有一行代码：
`onChange(value => console.log(value!.name))`
这个value!.name是什么写法啊，有相关的语法介绍或文档吗？或者是笔误？

**Comment by ascoders** [comment]
是 ts 的语法，另外也有一套 stage1 提案：[proposal-optional-chaining](https://github.com/tc39/proposal-optional-chaining)。

目前来看语法不太一样，分别是 `!.` 与 `?.`。

**Comment by nicewahson** [comment]
组件分的这么细，之间的通信怎么解决呢？

**Comment by ascoders** [comment]
@nicewahson 通过很多数据流框架的依赖注入可以解决。

**Comment by liutian** [comment]
看场景，我觉得大部分场景分这么细都是给自己找罪受或者给接盘的人找罪受，当然如果你恰好遇到那一小部分特殊场景，组件细分肯定是有好处的

**Comment by dancerphil** [comment]
> 看场景，我觉得大部分场景分这么细都是给自己找罪受或者给接盘的人找罪受，当然如果你恰好遇到那一小部分特殊场景，组件细分肯定是有好处的

这篇文章是 2017 年的，不要用现在的视角看。
