### ISSUE TITLE
精读周刊反思

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#47]
到今天，精读周刊一共发了 33 期，也就是坚持了 33 个星期，8 个多月。

我认为聚合周刊是一种知识的发散，可以提高知识“广度”，而精读每周只选一篇，尤其结合自身的思考，希望能提高知识的”深度“。

在这 8 个月中，所有文章都由我们内部同学完成，我承担了大部分，这与我的预期有所偏差，我希望精读能集思广益，防止成为我个人的笔记。因为业务繁忙，所以不少期的内容偏少，质量也不够高。

精读写作的流程分为 **引言** - **内容概要** - **精读** - **总结**。

每周选择文章都很纠结，但最终为什么会选择那一篇，这就是引言的意义。

内容概要不是翻译，而是对文章的总结，我们每次抱着学习的态度去阅读选文，在学习到知识的同时，散发出一些感悟形成了精读。

总结很多时候也许是多余的，内容也比较含糊，甚至与文章标题相反。许多知识点都是发散的，精读没必要，也没有能力给每个文章、每个知识点一个结论。去享受 “读” 的过程，并养成读后思辨的习惯，应该是精读真正的作用。

**Comment by huxiaoyun** [comment]
大家参与内容才会丰富起来，每个人关注点都不同。我感觉精读的内容太局限于技术细节了，普适性的文章更能吸粉....微信公众号也搞一搞？

**Comment by zhaosiwen1949** [comment]
还是希望多介绍一些技术细节吧，说实话普适性的文章很多公众号都能做，如果《精读周刊》也做的话，反而丧失了特色，不如鼓励大家投稿
