### ISSUE TITLE
精读《When You “Git” in Trouble: a Version Control Story》

### ISSUE THREAD

**Issue by twobin** [dt-fe/weekly#49]
精读《When You “Git” in Trouble: a Version Control Story》

本期我们看一篇比较轻松的文章，与 git 相关，大家可以讲讲自己与 git 的故事，如何通过 git 解决各式各样的冲突，以及多年使用 git 老司机们的心得和感悟。
精读不仅仅只关注于文章本身，文章只是个引子，更希望大家积极参与互动与讨论，才是精读的精髓之处。

本期精读文章地址：https://hackernoon.com/when-you-git-in-trouble-a-version-control-story-97e6421b5c0e

参与讨论地址：https://github.com/dt-fe/weekly/issues/49

**Comment by ascoders** [comment]
看到我司有三种 git 开发方式，分别是主干部署、分支部署和 gitflow，个人项目的话主干部署真的很方便，非常适合快速迭代。不过对外项目基本都不敢用主干部署，风险太高。

**Comment by huxiaoyun** [comment]
项目基本都按人负责，而且基本都是一个人对多个项目，master部署不要太爽歪歪.... 现在后端应用都是强制分支开发，部署的时候自动合并，前端就没固定到流程中，感觉以后也可以放到工程体系中优化哦~

**Comment by twobin** [comment]
![image](https://user-images.githubusercontent.com/3983192/34076511-7b2db15a-e324-11e7-8e7f-e80ebdbb6e44.png)
![image](https://user-images.githubusercontent.com/3983192/34076544-9e24bb62-e325-11e7-8a82-c71577d9589f.png)
![image](https://user-images.githubusercontent.com/3983192/34076684-6e7c5f74-e329-11e7-91e6-8fdf0a250c32.png)
![image](https://user-images.githubusercontent.com/3983192/34077156-cac98c2c-e336-11e7-80ff-e636a635c214.png)
![image](https://user-images.githubusercontent.com/3983192/34077176-a7da8d28-e337-11e7-855c-3e77f6c610f7.png)
![image](https://user-images.githubusercontent.com/3983192/34077197-718376da-e338-11e7-9b73-bc437b9b4f83.png)
![image](https://user-images.githubusercontent.com/3983192/34077217-3201a1de-e339-11e7-87dc-f7b3b358ecb5.png)
![image](https://user-images.githubusercontent.com/3983192/34077239-d081bd12-e339-11e7-941c-00f296936f05.png)
![image](https://user-images.githubusercontent.com/3983192/34077284-39dc23c8-e33b-11e7-86d7-794fa51d11c9.png)
![image](https://user-images.githubusercontent.com/3983192/34078157-79aeaa84-e34f-11e7-93d9-49d807daa3f9.png)
![image](https://user-images.githubusercontent.com/3983192/34078169-ed3a2db6-e34f-11e7-8a8d-f5d902584ed0.png)
![image](https://user-images.githubusercontent.com/3983192/34078228-175d7282-e351-11e7-9292-167e4c937bc4.png)
![image](https://user-images.githubusercontent.com/3983192/34078312-b9a9edc6-e352-11e7-835e-63d05caefd29.png)
![image](https://user-images.githubusercontent.com/3983192/34078372-14331b5e-e354-11e7-83dd-717aee47af4e.png)
![image](https://user-images.githubusercontent.com/3983192/34078398-91b8b58e-e354-11e7-9024-5f045062d67c.png)
![image](https://user-images.githubusercontent.com/3983192/34078542-59591b5e-e357-11e7-8ab5-7e2732dd354f.png)
![image](https://user-images.githubusercontent.com/3983192/34078587-e37f3c5a-e357-11e7-9413-da26ac5c868d.png)
