### ISSUE TITLE
精读《how we position and what we compare》

### ISSUE THREAD

**Issue by huxiaoyun** [dt-fe/weekly#50]
本篇文章以一个简单的例子，抽丝剥茧细数讲述如何面向用户可视化设计，化繁为简，化多为少，探索用户最终的目的，如何一张图中体现N张图的含义。具体内容，请和我一起走进 story telling data 系列 - how we position and what we compare [http://www.storytellingwithdata.com/blog/2017/12/14/how-we-position-and-what-we-compare](http://www.storytellingwithdata.com/blog/2017/12/14/how-we-position-and-what-we-compare)          <---- 此处应该有 x 档案 bgm ....
 
提前剧透：

![image](https://user-images.githubusercontent.com/4345248/34043844-b5d85ef6-e1dd-11e7-8f9b-22966f5c7ce6.png)

如何从左图变化到右图，难道作者是个拥有魔法棒的小仙女，还是可以点石成金的老神仙？？一起详细看文章，魔法是如何修炼成功的。

![image](https://user-images.githubusercontent.com/4345248/34043969-1de22298-e1de-11e7-86bb-955080302b08.png)

哎哟，这里没有内容咯~~~ 评论区等你哦~

**Comment by jasonslyvia** [comment]
想到之前看过一篇类似讲图表会骗人的文章，通过调整坐标轴的基数让原本差异不大的几组数据显得差异特别大 https://blog.heapanalytics.com/how-to-lie-with-data-visualization/

**Comment by huxiaoyun** [comment]
@jasonslyvia    是的呀。 人眼通过斜率和高度来对比差异，如果一不留神很容易被骗了。这让我想到，数据和语言一样，换种方式表达，翻译出来的意思就完全不同了，如果数据的表达方式能和语言一样，有一些固定的语法和规则，是不是能够减少表现上的歧义呢？

**Comment by ascoders** [comment]
人脑处理图形效率高于文字嘛，前端要做的也是提升人机交互效率，通过图形可以几倍甚至几百倍提高理解速度。

深度学习+可视化方向，就是不但让人类读懂图，让机器也读懂。未来可能很少会接触到数据化的数据，图形化数据可能成为标配，基于此的抽象会更有用，比如文中的图表转换。。
