### ISSUE TITLE
精读《dob - 框架使用》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#53]
本系列分三部曲：《框架实现》 《框架使用》 与 《跳出框架看哲学》，这三篇是我对数据流阶段性的总结，正好补充之前过时的文章。

这次写第一部 《框架使用》。对 dob 的使用方式做介绍，同时对前端数据流工程实践做一些分类。

**Comment by masx200** [comment]
现在已经是2019年了是时候抛弃class组件啦！应该基于react hooks开发一套状态管理工具了


推荐几个原创开源项目

vueJS全局状态管理库
https://github.com/masx200/vue-simple-global-state-store-manager

 reactJS全局状态管理库 
https://github.com/masx200/react-simple-global-state-store-hook

可能是最简单好用的状态管理库！
