### ISSUE TITLE
精读《The Cost Of JavaScript》

### ISSUE THREAD

**Issue by fanhc019** [dt-fe/weekly#61]
网页中的 js 执行需要哪些代价？我们的第一反应就是『下载到本地』和『客户端执行』两个。那针对于这两点，作为开发者我们都能做哪些优化。
1. 网络环境我们无法左右的，还有哪些方式可以做到让代码更快加载。压缩、缓存？还有其他方式吗？压缩是 minify 还是 compress 呢？
2. 相对于其他同样大小的静态文件而言，js 在客户端的执行更加昂贵。js 需要在客户端完成解析和执行，又有哪些方式可以让代码更快呢？

本期精读文章地址：https://medium.com/dev-channel/the-cost-of-javascript-84009f51e99e 需要翻墙

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/37806252-f5946434-2e79-11e8-80ec-83e05956474b.png)
