### ISSUE TITLE
精读《React's new Context API》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#64]
文章地址：https://tinyletter.com/kentcdodds/letters/react-s-new-context-api 

聊聊 context 的新 api。

**Comment by crimx** [comment]
链接后面的 `。` 分一下 :laughing:  ，或者用 `<>`  

<https://tinyletter.com/kentcdodds/letters/react-s-new-context-api>

**Comment by BlackGanglion** [comment]
知乎回答了一发，也可以作为精读参考：https://www.zhihu.com/question/267168180/answer/324650336
详细了解建议看 RFC：https://github.com/reactjs/rfcs/blob/master/text/0002-new-version-of-context.md
