### ISSUE TITLE
精读《webpack4.0 升级指南》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#66]
最近全网搜遍了 webpack4.0 相关文档，把项目脚手架升级到 webpack4，踩了很多坑。

最后整理出一套 typescript + webpack4.0 比较完整的经验，分享给大家，同时分享一下 v3 升级 v4 要注意的地方。

**Comment by DanielWLam** [comment]
期待

**Comment by ffxiang** [comment]
w4 确实比 w3 好用。逐渐踏上 傻瓜配置之路。 不用再去配置各种繁琐的插件，只用传参。

**Comment by sunorry** [comment]
@ascoders 你们的脚手架是开源的吗？我能学习下吗？

**Comment by ascoders** [comment]
@sunorry  是开源的，给你传送门：[Pri](https://github.com/prijs/pri)。

**Comment by LeonAppDev** [comment]
开头的这句话有点没明白，我的理解node api 应该是用来在源代码里面动态使用webpack的功能加入的吧？ 不知道我的理解对不对
>笔者尝试了 webpack node api，尝试了很久，发现被坑了。文档里只字未提 mode 模式，4.0 环境下 compiler 总是提示没有 mode 的 warning。
