### ISSUE TITLE
如何保时保质的产出文章？

### ISSUE THREAD

**Issue by yooungt13** [dt-fe/weekly#67]
很厉害，坚持了4个月了。想请教下产出一篇文章的过程。

**Comment by ascoders** [comment]
我是周一选题目，周五～周末写文章，写精读最重要的环节是选题，我会参考许多前端周刊，或者比较有意义的前端代码库，先读一读，再结合自己的经验谈谈。

一开始觉得写文章很难，但随着文章越写越多，会发现越来越好写。知识与知识碰撞起来会发生化学反应，找几个知识点结合一下，就是一篇文章啦 ^_^。

也欢迎大家谈谈自己的经验。

**Comment by zhoukekestar** [comment]
> 会参考许多前端周刊

有哪些优质来源？推荐一波前端周刊哈，或前端一手来源的 twitter，medium 账号？

**Comment by ascoders** [comment]
@zhoukekestar [这里](https://github.com/dt-fe/weekly/issues/2)列出了精读素材来源，欢迎补充。

**Comment by lanzhiheng** [comment]
感谢分享。
