### ISSUE TITLE
精读《Compilers are the New Frameworks》

### ISSUE THREAD

**Issue by twobin** [dt-fe/weekly#69]
本期精读文章 [《Compilers are the New Frameworks》](https://tomdale.net/2017/09/compilers-are-the-new-frameworks/)

前端开发一贯的使用方式，工具是工具，库是库，泾渭分明。而近来，我们发现工具和库其实可以糅合在一起，工具也是框架的一部分。 通过约定、自动生成和解析代码等方式来辅助开发，减少开发者要写的代码量，[UmiJs](https://github.com/sorrycc/blog/issues/58) 正是这样一个包含了工具&路由的开发框架。

大家可以各抒己见，讨论你对上述方式看法，讨论 UmiJS 的优劣性，讨论你对未来前端开发&框架的看法。

**Comment by twobin** [comment]
![image](https://user-images.githubusercontent.com/3983192/37875422-882e5cf2-3071-11e8-873f-497d45040084.png)

**Comment by twobin** [comment]
![image](https://user-images.githubusercontent.com/3983192/37875442-e3e03a5c-3071-11e8-9186-b65843520aa0.png)

**Comment by Jostar1024** [comment]
Compilers are the New Frameworks这文章的观点，我觉得大体上是说：Native App 怎么发展的，接下来Web App 也会向同一个方向发展，优化技术本质上是相同的，不同的是Web所在的浏览器和Native App 的所在操作系统上的区别。因为存在这些区别，优化技术还不能照搬，需要再次思考。

Umijs想法很不错，但会不会做的太大了？博客上显示好像这是个个人项目，日后要维护这个项目感觉很吃力。如果React官方多做一个*推荐配置*，是不是就和这个项目冲突了？

**Comment by Jostar1024** [comment]
嗯嗯，如果是整个团队都在参与的话就能理解了。。。

**Comment by tomzhang** [comment]
总体思路非常正确。当下的技术栈都是集中化和业务-框架剥离。通过前端层的组件化框架配合后端的SERVERLESS业务服务单元来进行快速产品迭代开发
