### ISSUE TITLE
精读《Elements of Web Development》

### ISSUE THREAD

**Issue by boyangwang** [dt-fe/weekly#71]
本周精读, 来总结一下web开发都有些什么环节? 有哪些知识块和技能点? 是不是像xx速成班宣传的一样, 培训三个月, 经验顶三年, 入职BAT, 年薪三十万?

https://medium.com/coderbyte/a-guide-to-becoming-a-full-stack-developer-in-2017-5c3c08a1600c

https://medium.com/codingthesmartway-com-blog/the-2018-roadmap-to-fullstack-web-development-8884ff02557a

https://www.lynda.com/learning-paths/Web/become-a-full-stack-web-developer

**Comment by ascoders** [comment]
希望有些深入的思考，不要蜻蜓点水的罗列知识点～

**Comment by boyangwang** [comment]
虽然这次是罗列知识点, 但我想也很有意义. 对于学习的人来说, 提供一个路线图. 对从业者来说, 对全局有更好的把控, 利于看到自己的强项和不足. 对组建团队, 更能起到一个点将谱的作用

在网上我没有搜到任何深入全面的总结, 提供的那几篇已经算稍微好一些的了. 其他的要么太过笼统(前端-后端-数据-运维, 完毕)要么太细太窄(并不是不好, 只是和本文性质不一样)

Generalist和Specialist之间永远是一对辩证矛盾, 持续思考~

**Comment by ascoders** [comment]
整体还行，列的例子有点短，最好用中文写～
