### ISSUE TITLE
精读《插件化思维》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#75]
插件化思维可以用来做技术工具，前端框架，或者做项目，一个合格的技术规划者应当拥有插件化思维。

可惜这方面文章比较少，除了零星的设计模式启发之外，很少能看到介绍如何做插件化的文章。笔者在经历许多项目的洗礼后，尝试总结一下，帮助大家养成插件化思维。

**Comment by atian25** [comment]
文章地址？

**Comment by ascoders** [comment]
@atian25 哎，找不到文章啊，就是想写这个主题的，有没有推荐文章？

我准备从做过的项目，以及看过的框架，cli 工具设计理念入手来分析。有文章指导就更好啦！

**Comment by atian25** [comment]
也没有，不过这块倒是接触不少。

FIS，Egg 都是强插件化理念的。

**Comment by ascoders** [comment]
这俩我都是忠实用户，哈哈。

有点慌，因为这个文章是写给做架构的同学看的，写完后如有理解不足之处希望批评指正，我这次先献丑了！

**Comment by atian25** [comment]
洗耳恭听~

**Comment by ascoders** [comment]
@huxiaoyun 说的更像 interface（接口）的定义，做技术项目需要的插件化思维是更上层的概念，要考虑的点也更多。

比如如何加载插件？如何定义插件语法？支持一套还是几套插件？核心也用插件写吗，要注意拿捏到何种分寸？哪些项目可以用插件机制做，带来的好坏处如何权衡，等等。

**Comment by ascoders** [comment]
上面先抛个砖，如果能吸引一些讨论，文章也会更好写一些。

**Comment by CharlieLau** [comment]
![image](https://user-images.githubusercontent.com/8924424/38799573-6351a72c-4197-11e8-8c97-d942816a9417.png)

**Comment by linonetwo** [comment]
我之前整理了一些可以参考的文章 http://onetwo.ren/%E5%89%8D%E7%AB%AF%E6%8F%92%E4%BB%B6%E7%B3%BB%E7%BB%9F%E8%AE%BE%E8%AE%A1/#%E5%8F%82%E8%80%83
之前想做一个支持插件的笔记系统来着，不过坑了，所以我写的那篇文章也太监了。

**Comment by usernamedd** [comment]
我是想看桌面程序的插件化思想的，结果这里的是更灵活的前端的东西，但是思想有相同的地方，系统留一些切口供插件插入。想深入插件化开发模式，可以参考Visual studio  , visual studio code ，ellicpse，但是都是桌面程序的例子。
最后，闲着没事把这个issue关了弄啥

**Comment by linonetwo** [comment]
@usernamedd 现在很多桌面程序就是用 electron 开发的，我最近在开发跨平台战棋游戏，用的就是 electron + react + pixi

**Comment by usernamedd** [comment]
> @usernamedd 现在很多桌面程序就是用 electron 开发的，我最近在开发跨平台战棋游戏，用的就是 electron + react + pixi

嗯，不错，有开源地址吗，欣赏学习一下

**Comment by linonetwo** [comment]
@usernamedd 游戏是 https://github.com/linonetwo/Eternity-Foundation 还刚开始开发

mod 系统是 https://github.com/linonetwo/Eternity-Foundation/blob/634ccd4e31784c855f6d8f3e1036bf070a196b6d/src/redux/models/mod.ts#L5 ，其实是把一些 API 暴露给 new Function ，载入用户脚本，利用 electron 的 contextIsolation 沙盒保证 mod 代码没法作恶。

**Comment by Pines-Cheng** [comment]
推荐 VSCode/[Theia](https://github.com/eclipse-theia/theia) 源码里面的 Extension/Plugin 设计，基于是一个强大的、轻量级的 IoC 容器  [InversifyJS](https://github.com/inversify/InversifyJS)，高级优雅而又功能强大。整个 IDE 都是基于 Extension 组成的，对外提供 Plugin 机制进行拓展。

参考：[Authoring Theia Extensions](https://theia-ide.org/docs/authoring_extensions/) 以及 [Authoring Theia Plug-ins](https://theia-ide.org/docs/authoring_plugins/)

**Comment by twinkle77** [comment]
https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/53.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%8F%92%E4%BB%B6%E5%8C%96%E6%80%9D%E7%BB%B4%E3%80%8B.md

**Comment by Echohzy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已收到。

**Comment by linonetwo** [comment]
[https://wiki.onetwo.ren/前端插件系统设计](https://wiki.onetwo.ren/#%E5%89%8D%E7%AB%AF%E6%8F%92%E4%BB%B6%E7%B3%BB%E7%BB%9F%E8%AE%BE%E8%AE%A1)
