### ISSUE TITLE
我想问问，有哪些工具可以有效的订阅这些github上面的文章资源？

### ISSUE THREAD

**Issue by whileLooper** [dt-fe/weekly#81]
我平常都是用feedly来订阅rss
github repo里面的这些可以做到推送吗？
还是只能靠 github自己的watch，在email里面查看？

**Comment by Colafornia** [comment]
@whileLooper 自荐一个我做的 https://github.com/Colafornia/little-robot，工作日推送到微信

历史记录和RSS源参考项目 issue

**Comment by Songkeys** [comment]
@whileLooper 

> github-issue-rss

这个貌似只能订阅 open 的 issues，URL filter 传参无效。而这个仓库的周刊 issue 都是发了就立马关掉的……也没有 release，commit 记录也很乱……很难订阅。

目前在用 hugiin 抓首页的 md 文件来订阅。

不知各位有没有更好的办法，或者仓库作者有没有弄个官方订阅源让大家更方便订阅的计划？

**Comment by giscafer** [comment]
![qr400](https://user-images.githubusercontent.com/8676711/53096878-20cb4800-355b-11e9-8537-fc9db51cbcb5.jpg)

有现成小程序，我搞的，可以了解一下，欢迎提建议。

@whileLooper @Songkeys @Colafornia

**Comment by zWingz** [comment]
可以用rsshub

**Comment by Songkeys** [comment]
@giscafer 

感谢，之前有看过和用过这个，非常棒的小程序，辛苦了！但还是比较喜欢 RSS 模式，集中起来看比较方便。

@zWingz 

请问你正在使用吗？我之前查过，好像 RSSHub 也不支持被关闭的 issue 的查询？我这几天正准备提个 PR。

**Comment by giscafer** [comment]
@Songkeys RSS个人也有用inoreader，充足时间和认真看会选择 inoreader rss来看，小程序仅是碎片时间看，10分钟以内，了解为止的。

**Comment by zWingz** [comment]
@Songkeys 被关闭的issues我觉得不需要看了吧..我用`Reeder`订阅了
