### ISSUE TITLE
精读《重新思考 Redux》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#83]
本周精读是： [重新思考 Redux](https://hackernoon.com/redesigning-redux-b2baee8b8a38)

作者也是 [rematch](https://github.com/rematch/rematch) 的作者。rematch 是我很喜欢的一个 redux 库，提供了框架级别的插件机制让人耳目一新。

让我们一起重新思考 Redux，以及从 rematch 中能学到什么吧！

**Comment by Usey95** [comment]
粗略看了一下，有点像dva?

**Comment by Hiufan** [comment]
rematch和dva的实现确实很像，有什么显著性的区别或者说优势么？

**Comment by ascoders** [comment]
@Hiufan 用起来更自然，比如用函数调用代替 `put` 或者 `dispatch`。其他方面几乎没区别，包括插件机制和很类似，现在对 redux 优化都集中在使用体验，比如更好的支持 Typescript，而在功能上一般没有区别。

**Comment by zaaack** [comment]
@ascoders 还有彻底跑起redux，走向静态类型elm风格，比如 hydux。。 https://github.com/hydux/hydux/

**Comment by athrunsun** [comment]
> dva 之后，有许多基于 redux 的状态管理框架

可以请教一下有哪些吗？

**Comment by masx200** [comment]
https://github.com/masx200/react-simple-global-state-store-hook

使用 react hooks 实现的简单全局状态管理 react-simple-global-state-store-hook

仅仅使用44行代码写成的极简react全局状态管理库

**Comment by masx200** [comment]
redux这么复杂，超级难用，这谁顶得住啊

**Comment by Tan90Qian** [comment]
@masx200 那就用mobx吧！我感觉redux用起来不舒服的地方就是dispatch时候需要写字符串type而不是直接用类似对象属性名的形式去调用，导致type匹配失败的场景无法在编译时被发现。rematch提供的新的dispatch形式，以及mutable式的修改store，跟mobx也没太大差别了。无非是保留了通过reducer和effect的命名去分隔了副作用的机制

**Comment by DiamondYuan** [comment]
> @masx200 那就用mobx吧！我感觉redux用起来不舒服的地方就是dispatch时候需要写字符串type而不是直接用类似对象属性名的形式去调用，导致type匹配失败的场景无法在编译时被发现。rematch提供的新的dispatch形式，以及mutable式的修改store，跟mobx也没太大差别了。无非是保留了通过reducer和effect的命名去分隔了副作用的机制

如果是 ts 可以试试看 dva-model-creator，或者 typescript-fsa ，完全抛弃了裸写字符串的模式。
