### ISSUE TITLE
精读《现代 js 框架存在的根本原因》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#84]
原文地址：https://medium.com/dailyjs/the-deepest-reason-why-modern-javascript-frameworks-exist-933b86ebc445

**Comment by MicleMing** [comment]
1. 个人觉得浏览器应该做的是更底层的事，比如新的人机交互，更快的加载和渲染速度等等，而UI与state同步的事，其实加上一个中间层就能搞定，react、vue等都是一个中间层，这一层应该开放给开发者进行处理。
2. 状态与UI同步的问题我个人理解是一个状态机处理状态的问题，整个应用是一个状态机，处理不同的输入。而能把应用变成状态机的只能是js，html和css都不行。所以以js为中心进行前端开发是趋势，除非找到新的编程模型
