### ISSUE TITLE
精读《Typescript2.0 - 2.9》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#85]
精读原文是 typescript 2.0-2.9 的文档。

其中 2.0 ～ 2.8 的地址：http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html
2.9 草案地址：https://blogs.msdn.microsoft.com/typescript/2018/05/16/announcing-typescript-2-9-rc/

通过长期工作，我意识到深入掌握 typescript 需要**刻意练习**，即便 2.0-2.9 的新特征可以优雅解决许多业务问题，但我们不了解也就并不会用，更糟糕的是 typescript 的深入语法是无法从业务代码中锻炼的，因为我们总是能忍受糟糕的业务代码，甚至是不知道原来代码可以优化。

只有先了解它，才能更“聪明”的解决问题，这周我们一起刻意练习 typescript 吧！

**Comment by crimx** [comment]
2.8 解决了很多痛点，收集了几个相关的 recipes 分享一下

1. Deep Readonly
   ```ts
   interface DeepReadonlyArray<T> extends ReadonlyArray<DeepReadonly<T>> {}
   
   type DeepReadonlyObject<T> = {
       readonly [P in keyof T]: DeepReadonly<T[P]>
   }
   
   type DeepReadonly<T> =
       T extends (infer R)[]
         ? DeepReadonlyArray<R>
         : T extends Function
           ? T
           : T extends object
             ? DeepReadonlyObject<T>
             : T
   ```

2. Mutable
   ```ts
   type Mutable<T> = { -readonly [P in keyof T]: T[P] }
   ```

3. 利用 ReturnType 直接拿 type 可以减少 boilerplate

还有两个很常见但一直没有被收进的

1. Diff 
   ```ts
   type Diff<T extends string, U extends string> = ({[P in T]: P } & {[P in U]: never } & { [x: string]: never })[T]
   ```
2. Omit
   ```ts
   type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>>
   ```

**Comment by atian25** [comment]
2.8 新出的一些新特性，才使得我们的 Egg 的 TS 化完美了不少，https://github.com/whxaxes/blog/issues/12

**Comment by ascoders** [comment]
@crimx TS `2.8` 内置了 Exclude 作为官方版的 `Diff`。

**Comment by crimx** [comment]
@ascoders 看到了！谢谢提醒
