### ISSUE TITLE
更新会变慢。。??

### ISSUE THREAD

**Issue by wusiquan** [dt-fe/weekly#86]
树低了，更新操作，不也是变快吗？

**Comment by wusiquan** [comment]
貌似issue不是针对，单个md的。。。我想说的是第9篇

**Comment by ascoders** [comment]
> 树低了，更新操作，不也是变快吗？

这段话看上去没问题，这个疑问是针对的是哪一段文字呢？

**Comment by wusiquan** [comment]
> 但是，当树越宽（子节点越多）时，相应树的高度会下降，随之查询效率会提高，但更新效率则会下降（试想一下极限情况，就相当于线性结构）。为寻求更新与查询的平衡，我们便选择了 5bit 一分割。

感谢回答，这一段，极限情况指的 O -- O -- O -- O -- O... 是这种吗？

**Comment by wusiquan** [comment]
哦，大致明白了，你这里提到的更新，应该指的是批量更新操作。。。
如果就单独更新操作的作用，应该是O(~1) 更接近常数
然后"引用操作耗费了"这大概涉及到RAM的读写方面的事了。。。
