### ISSUE TITLE
精读《如何利用 Nodejs 监听文件夹》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#87]
精读文章：[how-to-watch-for-files-changes-in-node-js](http://thisdavej.com/how-to-watch-for-files-changes-in-node-js/)。

一般监听目录变化，我们都会使用 [chokidar](https://github.com/paulmillr/chokidar) [watch](https://github.com/mikeal/watch) 等库，这篇文章介绍了监听目录的实现细节与注意点，值得学习一下。

**Comment by wzjsun** [comment]
你好，watch是不是不能监听软连接啊，如果可以，怎么监听呢

**Comment by ascoders** [comment]
@wzjsun  可以参考这段代码：https://github.com/paulmillr/chokidar/blob/master/lib/nodefs-handler.js#L294
应该是直接监听软连接指向的文件路径。
