### ISSUE TITLE
精读《如何在 nodejs 使用环境变量》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#89]
本周精读的文章是：https://medium.freecodecamp.org/heres-how-you-can-actually-use-node-environment-variables-8fdf98f53a0a

**Comment by crimx** [comment]
这期好好笑 😂 金句频现

**Comment by liuxsen** [comment]
大神  怎么找见这么多优秀的国外的blog的？

**Comment by ascoders** [comment]
@liuxsen [周刊参考池](https://github.com/dt-fe/weekly/issues/2)
