### ISSUE TITLE
精读《手写 SQL 编译器 - 词法分析》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#93]
又进入精读连载的季节！前端也学一点编译原理，通过后续几期的文章，一步步介绍如何手写一个 SQL 编译器。

系列文章分为：
手写 SQL 编译器 - 词法分析
手写 SQL 编译器 - 文法介绍
手写 SQL 编译器 - 语法分析
手写 SQL 编译器 - 递归下降
手写 SQL 编译器 - 函数式递归下降
手写 SQL 编译器 - 分支预测

如果后续编不下去也许会跳票～

**Comment by whinc** [comment]
期待😄

**Comment by ascoders** [comment]
@dongsuo 是原创的。

**Comment by jonirrings** [comment]
看了楼主的贴子，捡起了大学没选的课《编译原理》，的确是一门很有意思的课程。🥳

**Comment by davidkhala** [comment]
@ascoders 《手写 SQL 编译器 - 词法分析》这是一本实体书么？还是电子书？有原书的链接么？

**Comment by ascoders** [comment]
@davidkhala 《手写 SQL 编译器》整个系列都是我原创，背后参考了许多编译原理相关书籍的理论，并结合了实际编码经验汇总而成。

基于这篇文章的代码我也开源了，发出来参考：https://github.com/ascoders/syntax-parser

**Comment by JiaLiangC** [comment]
帅的一批

**Comment by Echohzy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已收到。
