### ISSUE TITLE
精读《手写 SQL 编译器 - 语法分析》

### ISSUE THREAD

**Issue by ascoders** [dt-fe/weekly#95]
又进入精读连载的季节！前端也学一点编译原理，通过几期的文章，一步步介绍如何手写一个 SQL 编译器。

系列文章分为：
[手写 SQL 编译器 - 词法分析](https://github.com/dt-fe/weekly/blob/master/64.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%89%8B%E5%86%99%20SQL%20%E7%BC%96%E8%AF%91%E5%99%A8%20-%20%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E3%80%8B.md)
[手写 SQL 编译器 - 文法介绍](https://github.com/dt-fe/weekly/blob/master/65.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%89%8B%E5%86%99%20SQL%20%E7%BC%96%E8%AF%91%E5%99%A8%20-%20%E6%96%87%E6%B3%95%E4%BB%8B%E7%BB%8D%E3%80%8B.md)
手写 SQL 编译器 - 语法分析 new !
手写 SQL 编译器 - 分支预测

**Comment by maoyuyang** [comment]
写的真好

**Comment by sp42** [comment]
太深奥了。小白表示看不懂

**Comment by zgww** [comment]
我发现所谓的左递归，只是因为会陷入死循环，导致栈溢出。 
我的思路是：左递归用尝试法。 尝试0到n+1次递归， 当第n+1次递归，匹配失败，或者不能匹配更多的token, 就会认为最大匹配递归次数为  n。
